import Meta.Collatz.OperationalParity
import Meta.Arithmetic.CountdownGapContraction

/-!
# Countdown impact of Collatz operational parity

This file specializes the Collatz operational parity layer to the countdown
terminal intersection.
-/

namespace Meta
namespace EnrichedNatClosedStabilityInstance

open ClosedStabilityTheorem

/-! ## Countdown specialization -/

/-- The countdown closing side returns the terminal formed payload `n+2`. -/
def collatzCountdownClosingPayload
    (n : Nat) :
    Nat :=
  collatzClosingPayloadOfIntersection
    (countdownTerminalIntersection n)

/-- The countdown shadow side returns to a closing role. -/
def collatzCountdownShadowReturnRole
    (n : Nat) :
    NatEnrichedParityRole :=
  collatzShadowReturnRoleOfIntersection
    (countdownTerminalIntersection n)

/-- The countdown closing side has payload `n+2`. -/
theorem collatzCountdownClosingPayload_eq_n_plus_two
    (n : Nat) :
    collatzCountdownClosingPayload n = n + 2 := by
  unfold collatzCountdownClosingPayload
  rw [collatzClosingPayloadOfIntersection_eq,
    countdownArithmeticGapTerminalExcess_eq_n_plus_two]

/-- The countdown closing side has payload one step after terminal time. -/
theorem collatzCountdownClosingPayload_eq_terminalTime_succ
    (n : Nat) :
    collatzCountdownClosingPayload n = countdownTerminalTime n + 1 := by
  unfold collatzCountdownClosingPayload
  rw [collatzClosingPayloadOfIntersection_eq_terminalTime_succ,
    countdownTerminalIntersection_terminalTime_eq]

/--
The countdown shadow side returns to the closing role whose payload is
`3*(n+2)+2`.
-/
theorem collatzCountdownShadowReturnRole_eq_n_plus_two
    (n : Nat) :
    collatzCountdownShadowReturnRole n =
      NatEnrichedParityRole.closingExcess (3 * (n + 2) + 2) := by
  unfold collatzCountdownShadowReturnRole
  rw [collatzShadowReturnRoleOfIntersection_eq,
    countdownArithmeticGapTerminalExcess_eq_n_plus_two]

/--
The countdown shadow side returns to the closing role computed from one step
after terminal time.
-/
theorem collatzCountdownShadowReturnRole_eq_terminalTime_succ
    (n : Nat) :
    collatzCountdownShadowReturnRole n =
      NatEnrichedParityRole.closingExcess
        (3 * (countdownTerminalTime n + 1) + 2) := by
  unfold collatzCountdownShadowReturnRole
  rw [collatzShadowReturnRoleOfIntersection_eq_terminalTime_succ,
    countdownTerminalIntersection_terminalTime_eq]

/-! ## Countdown positive diagonal paths -/

/--
Generic countdown post-peak positive-window indexed parity.

This follows the bounded-window route generated by `countdownPostPeakWindow`.
It does not identify the produced pigeonhole collision with the explicit
terminal collision.
-/
def countdownPostPeakPositiveWindowIndexedDiagonalParity
    (n : Nat) :
    ArithmeticPositiveWindowIndexedDiagonalParity
      (countdownPrefixHeightCertificate n) :=
  arithmeticPositiveWindowIndexedDiagonalParityOfPostPeakWindow
    (countdownPostPeakWindow n)

/--
Generic Collatz positive operational diagonal step for the countdown
post-peak window.
-/
def countdownPostPeakPositiveCollatzDiagonalStep
    (n : Nat) :
    CollatzPositiveOperationalDiagonalStep
      (countdownPostPeakPositiveWindowIndexedDiagonalParity n) :=
  collatzPositiveOperationalDiagonalStepOfArithmetic
    (countdownPostPeakPositiveWindowIndexedDiagonalParity n)

/--
Explicit countdown terminal Collatz diagonal step.

This package keeps the canonical positive height witness separate from the
explicit terminal intersection.  The `n+2` claims are attached only to the
terminal intersection generated by `countdownTerminalWindowCollision`.
-/
structure CountdownPositiveTerminalCollatzDiagonalStep
    (n : Nat) :
    Type where
  heightWithWitness :
    NatTrajectoryFinitePrefixHeightWithPositiveDiagonalWitness countdownStep n
  heightWithWitness_eq :
    heightWithWitness = countdownPrefixHeightWithPositiveDiagonalWitness n
  terminalIntersection :
    PrimitiveMemoryReadingIntersection
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (countdownTerminalWindowCollision n))))
  terminalIntersection_eq :
    terminalIntersection = countdownTerminalIntersection n
  terminalIndexedParity :
    ArithmeticIndexedDiagonalParity terminalIntersection
  terminalIndexedParity_eq :
    terminalIndexedParity =
      arithmeticIndexedDiagonalParityOfIntersection terminalIntersection
  collatzStep :
    CollatzOperationalDiagonalStep terminalIntersection
  collatzStep_eq :
    collatzStep =
      collatzOperationalDiagonalStepOfIntersection terminalIntersection
  positiveWitness_eq_one :
    heightWithWitness.positiveDiagonal.positiveWitness = 1
  terminalFormedExcess_eq_n_plus_two :
    formedPositiveExcessOfIntersection terminalIntersection = n + 2
  shadowReturnRole_eq_n_plus_two :
    collatzStep.shadowReturnRole =
      NatEnrichedParityRole.closingExcess (3 * (n + 2) + 2)

/-- Canonical explicit countdown terminal Collatz diagonal step. -/
def countdownPositiveTerminalCollatzDiagonalStep
    (n : Nat) :
    CountdownPositiveTerminalCollatzDiagonalStep n where
  heightWithWitness :=
    countdownPrefixHeightWithPositiveDiagonalWitness n
  heightWithWitness_eq := rfl
  terminalIntersection :=
    countdownTerminalIntersection n
  terminalIntersection_eq := rfl
  terminalIndexedParity :=
    arithmeticIndexedDiagonalParityOfIntersection
      (countdownTerminalIntersection n)
  terminalIndexedParity_eq := rfl
  collatzStep :=
    collatzOperationalDiagonalStepOfIntersection
      (countdownTerminalIntersection n)
  collatzStep_eq := rfl
  positiveWitness_eq_one := rfl
  terminalFormedExcess_eq_n_plus_two :=
    countdownArithmeticGapTerminalExcess_eq_n_plus_two n
  shadowReturnRole_eq_n_plus_two :=
    collatzCountdownShadowReturnRole_eq_n_plus_two n

/-- The generic countdown post-peak path carries a Collatz positive step. -/
theorem countdownPostPeakPositiveCollatzDiagonalStep_carries_arithmetic
    (n : Nat) :
    (countdownPostPeakPositiveCollatzDiagonalStep n).collatzStep =
      collatzOperationalDiagonalStepOfIntersection
        (countdownPostPeakPositiveWindowIndexedDiagonalParity n).terminalIntersection :=
  rfl

/-- The explicit terminal package keeps the canonical positive witness at `1`. -/
theorem countdownPositiveTerminalCollatzDiagonalStep_positiveWitness_eq_one
    (n : Nat) :
    (countdownPositiveTerminalCollatzDiagonalStep
      n).heightWithWitness.positiveDiagonal.positiveWitness = 1 :=
  rfl

/-- The explicit terminal package carries terminal formed excess `n+2`. -/
theorem countdownPositiveTerminalCollatzDiagonalStep_terminalFormedExcess_eq_n_plus_two
    (n : Nat) :
    formedPositiveExcessOfIntersection
        (countdownPositiveTerminalCollatzDiagonalStep
          n).terminalIntersection =
      n + 2 :=
  countdownArithmeticGapTerminalExcess_eq_n_plus_two n

/-- The explicit terminal package carries the Collatz shadow return at `n+2`. -/
theorem countdownPositiveTerminalCollatzDiagonalStep_shadowReturnRole_eq_n_plus_two
    (n : Nat) :
    (countdownPositiveTerminalCollatzDiagonalStep n).collatzStep.shadowReturnRole =
      NatEnrichedParityRole.closingExcess (3 * (n + 2) + 2) :=
  collatzCountdownShadowReturnRole_eq_n_plus_two n

/-- The countdown closing regime is the formed dynamic regime. -/
theorem collatzCountdownClosingRegime_eq_formedRegime
    (n : Nat) :
    operationalParityRoles_closingRegime
        (arithmeticOperationalParityRolesOfIntersection
          (countdownTerminalIntersection n)) =
      dynamicParitySeparation_formedRegime
        (arithmeticDynamicParitySeparationOfIntersection
          (countdownTerminalIntersection n)) :=
  collatzClosingRegime_eq_formedRegime
    (countdownTerminalIntersection n)

/-- The countdown mediating regime is the shadow dynamic regime. -/
theorem collatzCountdownMediatingRegime_eq_shadowRegime
    (n : Nat) :
    operationalParityRoles_mediatingRegime
        (arithmeticOperationalParityRolesOfIntersection
          (countdownTerminalIntersection n)) =
      dynamicParitySeparation_shadowRegime
        (arithmeticDynamicParitySeparationOfIntersection
          (countdownTerminalIntersection n)) :=
  collatzMediatingRegime_eq_shadowRegime
    (countdownTerminalIntersection n)

/-- The countdown Collatz parity regimes keep the contracted parity projection. -/
theorem collatzCountdown_sameProjection
    (n : Nat) :
    parityProjection
        (operationalParityRoles_closingRegime
          (arithmeticOperationalParityRolesOfIntersection
            (countdownTerminalIntersection n))) =
      parityProjection
        (operationalParityRoles_mediatingRegime
          (arithmeticOperationalParityRolesOfIntersection
            (countdownTerminalIntersection n))) :=
  collatzOperationalParity_sameProjection
    (countdownTerminalIntersection n)

/-- The countdown Collatz parity regimes remain separated. -/
theorem collatzCountdown_separated
    (n : Nat) :
    operationalParityRoles_closingRegime
        (arithmeticOperationalParityRolesOfIntersection
          (countdownTerminalIntersection n)) =
      operationalParityRoles_mediatingRegime
        (arithmeticOperationalParityRolesOfIntersection
          (countdownTerminalIntersection n)) ->
        False :=
  collatzOperationalParity_separated
    (countdownTerminalIntersection n)

end EnrichedNatClosedStabilityInstance
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzCountdownClosingPayload
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzCountdownShadowReturnRole
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzCountdownClosingPayload_eq_n_plus_two
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzCountdownShadowReturnRole_eq_n_plus_two
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzCountdownClosingPayload_eq_terminalTime_succ
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzCountdownShadowReturnRole_eq_terminalTime_succ
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownPostPeakPositiveWindowIndexedDiagonalParity
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownPostPeakPositiveCollatzDiagonalStep
#print axioms Meta.EnrichedNatClosedStabilityInstance.CountdownPositiveTerminalCollatzDiagonalStep
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownPositiveTerminalCollatzDiagonalStep
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownPostPeakPositiveCollatzDiagonalStep_carries_arithmetic
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownPositiveTerminalCollatzDiagonalStep_positiveWitness_eq_one
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownPositiveTerminalCollatzDiagonalStep_terminalFormedExcess_eq_n_plus_two
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownPositiveTerminalCollatzDiagonalStep_shadowReturnRole_eq_n_plus_two
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzCountdownClosingRegime_eq_formedRegime
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzCountdownMediatingRegime_eq_shadowRegime
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzCountdown_sameProjection
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzCountdown_separated
/- AXIOM_AUDIT_END -/
