import Meta.Collatz.VisibleRoleDynamics

/-!
# Collatz internal state trajectory

This file packages the internal trajectory generated by the closure loop.

The trajectory is not an external numeric orbit.  Its states are operational
intersections, and its successor is the internal consumer already produced by
`collatzNextInternalIntersection`.
-/

namespace Meta
namespace EnrichedNatClosedStabilityInstance

/-! ## Internal states -/

/-- Internal Collatz state: a branch together with its operational intersection. -/
abbrev CollatzInternalState :=
  Sigma (fun branch : MemoryBranch =>
    PrimitiveMemoryReadingIntersection branch)

/-- Extract the operational intersection from an internal state. -/
def CollatzInternalState.intersection
    (state : CollatzInternalState) :
    PrimitiveMemoryReadingIntersection state.1 :=
  state.2

/-! ## Successor and trajectory -/

/-- Next internal state produced by the canonical closure consumer. -/
def collatzNextInternalState
    (state : CollatzInternalState) :
    CollatzInternalState :=
  match state with
  | Sigma.mk _branch intersection =>
      Sigma.mk
        (collatzNextInternalBranch intersection)
        (collatzNextInternalIntersection intersection)

/-- Internal trajectory generated by repeated closure consumption. -/
def collatzInternalStateTrajectory
    (state : CollatzInternalState) :
    Nat -> CollatzInternalState
  | 0 => state
  | t + 1 =>
      collatzNextInternalState
        (collatzInternalStateTrajectory state t)

/-- The internal trajectory starts at its input state. -/
theorem collatzInternalStateTrajectory_zero
    (state : CollatzInternalState) :
    collatzInternalStateTrajectory state 0 = state :=
  rfl

/-- The successor step of the internal trajectory. -/
theorem collatzInternalStateTrajectory_succ
    (state : CollatzInternalState)
    (t : Nat) :
    collatzInternalStateTrajectory state (t + 1) =
      collatzNextInternalState
        (collatzInternalStateTrajectory state t) :=
  rfl

/-! ## Visible role read from the next internal state -/

/--
The next internal role is the closing role read on the next internal
intersection.
-/
def collatzNextInternalStateRole
    (state : CollatzInternalState) :
    NatEnrichedParityRole :=
  match state with
  | Sigma.mk _branch intersection =>
      arithmeticClosingRoleOfIntersection
        (collatzNextInternalIntersection intersection)

/-- The next internal role is the closing role reinserted by terminality. -/
theorem collatzNextInternalStateRole_eq_closing
    (state : CollatzInternalState) :
    collatzNextInternalStateRole state =
      NatEnrichedParityRole.closingExcess
        (collatzDynamicClosureLoop state.intersection).peak := by
  cases state with
  | mk branch intersection =>
      exact
        collatzCurrentPeak_reinserted_in_nextInternalIntersection
          intersection

end EnrichedNatClosedStabilityInstance
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.EnrichedNatClosedStabilityInstance.CollatzInternalState
#print axioms Meta.EnrichedNatClosedStabilityInstance.CollatzInternalState.intersection
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzNextInternalState
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzInternalStateTrajectory
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzInternalStateTrajectory_zero
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzInternalStateTrajectory_succ
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzNextInternalStateRole
#print axioms Meta.EnrichedNatClosedStabilityInstance.collatzNextInternalStateRole_eq_closing
/- AXIOM_AUDIT_END -/
