import Carbone.CW1.Lean.ValenceCompletion

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.Carbone.CW0.carbonProjectionObstruction
#print axioms Meta.Carbone.CW0.CarbonWorld.step_eq_executeRepair
#print axioms Meta.Carbone.CW0.CarbonWorld.step_totalInventory
#print axioms Meta.Carbone.CW0.CarbonWorld.step_energyBalance
#print axioms Meta.Carbone.CW0.CarbonWorld.repairAt_energyDissipated_eq_requested
#print axioms Meta.Carbone.CW0.CarbonCoreAtlas.toGapRepairAlgebra
#print axioms Meta.Carbone.CW0.CarbonCoreAtlas.coreNext_eq_worldStep
#print axioms Meta.Carbone.CW0.twoPhaseCoreAtlas
#print axioms Meta.Carbone.CW0.twoPhaseCoreNext_eq_worldStep
#print axioms Meta.Carbone.CW0.twoPhaseCoreStep_organization
#print axioms Meta.Carbone.CW0.twoPhaseInitialCoreStep_preservesInventory
#print axioms Meta.Carbone.CW0.twoPhaseKernel_commutes
#print axioms Meta.Carbone.CW0.twoPhaseKernel_two_steps
#print axioms Meta.Carbone.CW1.twoPhaseMaintenance
#print axioms Meta.Carbone.CW1.twoPhaseMaterialMemory
#print axioms Meta.Carbone.CW1.twoPhaseMemory_sameProjection
#print axioms Meta.Carbone.CW1.twoPhaseMemory_reads_separated
#print axioms Meta.Carbone.CW1.twoPhaseCore_read_updates
#print axioms Meta.Carbone.CW1.twoPhaseCore_two_steps_organization
#print axioms Meta.Carbone.CW1.twoPhase_requestedResourcesAt_zero
#print axioms Meta.Carbone.CW1.twoPhase_requestedEnergyAt_one
#print axioms Meta.Carbone.CW1.twoPhaseEnergyThroughputMaintenance
#print axioms Meta.Carbone.CW1.twoPhaseResourceCoupledMaintenance
#print axioms Meta.Carbone.CW1.twoPhase_step_energyBalance
#print axioms Meta.Carbone.CW1.twoPhase_energyDissipated_eq_requested
#print axioms Meta.Carbone.CW1.chainSkeleton_implicitHydrogenProfile
#print axioms Meta.Carbone.CW1.bridgedSkeleton_implicitHydrogenProfile
#print axioms Meta.Carbone.CW1.chainSkeleton_neutralValenceInventory
#print axioms Meta.Carbone.CW1.bridgedSkeleton_neutralValenceInventory
#print axioms Meta.Carbone.CW1.chainConnectedCertificate
#print axioms Meta.Carbone.CW1.bridgedConnectedCertificate
#print axioms Meta.Carbone.CW1.c2h6oConstitutionalIsomerWitness
/- AXIOM_AUDIT_END -/
