name = "meta"
version = "0.1.0"
defaultTargets = ["Meta"]

[[require]]
scope = "FormalizedFormalLogic"
name = "Foundation"
rev = "master"

[[lean_lib]]
name = "Meta"

[[lean_lib]]
name = "Carbone"

[[lean_exe]]
name = "export_two_phase"
root = "Carbone.CW0.Lean.ExportTwoPhaseMain"

[[lean_exe]]
name = "export_cw1_energy"
root = "Carbone.CW1.Lean.ExportEnergyMain"
