import LocalSemanticClosure.Standalone.Clean.meta.Arithmetic.Countdown

/-!
# Arithmetic dynamic gap facade

This file closes the dynamic Nat layer before any mechanical reorganization.

It exposes the common dynamic row:

* formed trace;
* payload-only shadow;
* shared visible payload;
* positive terminal excess;
* projective obstruction;
* local recovery.

The key distinction is explicit:

* the canonical positive diagonal at height `n` has terminal excess `1`;
* the intrinsic countdown terminal collision at `n` has dynamic terminal
  excess `n + 2`.
-/

namespace LocalSemanticClosure
namespace Standalone
namespace Clean
namespace EnrichedNatClosedStabilityInstance

open ClosedStabilityTheorem

/-! ## Dynamic gap row -/

/--
Public row of an arithmetic dynamic gap.

The row records both sides of the projection collision: the enriched formed
trace and the payload-only shadow.  They have the same visible payload but are
separated as enriched traces.  The row also carries the obstruction and local
recovery generated by the same intersection.
-/
structure ArithmeticDynamicGapRow where
  formed : List NatTraceAtom
  shadow : List NatTraceAtom
  visible : List Nat
  terminalExcess : Nat
  sameVisible : tracePayloads formed = tracePayloads shadow
  separated : formed = shadow -> False
  obstruction :
    ProjectionObstruction
      (List NatTraceAtom)
      (List Nat)
      tracePayloads
  recovery :
    LocalProjectiveRecovery
      (List NatTraceAtom)
      (List Nat)
      tracePayloads
      NatInterfaceRepair

/--
Final row coupling an arithmetic dynamic gap with the recovered closed-stability
instance generated by the same dynamic source.
-/
structure ArithmeticDynamicClosedStabilityRow
    (branch : MemoryBranch) where
  gapRow : ArithmeticDynamicGapRow
  closedStability :
    RecoveredNonProjectiveClosedStabilityFromIntersection
      bidirectionalCompleteness
      branch
      (List NatTraceAtom)
      NatInterfaceWitness
      NatInterfaceRealization
      (List Nat)
      tracePayloads
      NatInterfaceRepair

/-- The dynamic gap row generated by an exact primitive intersection. -/
def arithmeticDynamicGapRowOfIntersection
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    ArithmeticDynamicGapRow where
  formed := formedTraceOfIntersection intersection
  shadow := payloadOnlyTraceOfIntersection intersection
  visible := tracePayloads (payloadOnlyTraceOfIntersection intersection)
  terminalExcess := formedPositiveExcessOfIntersection intersection
  sameVisible := formedTraceOfIntersection_same_payloadOnlyPayload intersection
  separated := formedTraceOfIntersection_ne_payloadOnlyTrace intersection
  obstruction := payloadProjectionObstructionOfIntersection intersection
  recovery := localProjectiveRecoveryOfIntersection intersection

/-! ## Repeated-index lock -/

/-- The primitive repeated-index intersection stores `secondTime` as excess. -/
theorem repeatedIndexIntersection_excess_eq
    (collision : RepeatedIndexCollision) :
    (repeatedIndexIntersection collision).excess = collision.secondTime :=
  rfl

/-- The terminal excess of a repeated-index dynamic gap is `secondTime + 1`. -/
theorem repeatedIndexTerminalExcess_eq
    (collision : RepeatedIndexCollision) :
    formedPositiveExcessOfIntersection
      (repeatedIndexIntersection collision) =
        collision.secondTime + 1 :=
  rfl

/-- The repeated-index formed trace and payload-only shadow share payload. -/
theorem repeatedIndexDynamicGap_sameVisible
    (collision : RepeatedIndexCollision) :
    tracePayloads
      (formedTraceOfIntersection (repeatedIndexIntersection collision)) =
        tracePayloads
          (payloadOnlyTraceOfIntersection
            (repeatedIndexIntersection collision)) :=
  formedTraceOfIntersection_same_payloadOnlyPayload
    (repeatedIndexIntersection collision)

/-- The repeated-index formed trace is not the payload-only shadow. -/
theorem repeatedIndexDynamicGap_separated
    (collision : RepeatedIndexCollision) :
    formedTraceOfIntersection (repeatedIndexIntersection collision) =
      payloadOnlyTraceOfIntersection (repeatedIndexIntersection collision) ->
        False :=
  formedTraceOfIntersection_ne_payloadOnlyTrace
    (repeatedIndexIntersection collision)

/-- Public dynamic gap row generated by a repeated-index collision. -/
def repeatedIndexDynamicGapRow
    (collision : RepeatedIndexCollision) :
    ArithmeticDynamicGapRow :=
  arithmeticDynamicGapRowOfIntersection
    (repeatedIndexIntersection collision)

/-- Final repeated-index row: dynamic gap plus recovered closed stability. -/
def repeatedIndexDynamicClosedStabilityRow
    (collision : RepeatedIndexCollision) :
    ArithmeticDynamicClosedStabilityRow
      (repeatedIndexBranch collision) where
  gapRow := repeatedIndexDynamicGapRow collision
  closedStability := repeatedIndexClosedStabilityInstance collision

/-! ## Trajectory lock -/

/--
A repeated value in a Nat trajectory has terminal excess `secondTime + 1`.
-/
theorem trajectoryCollision_terminalExcess_eq
    {step : Nat -> Nat}
    {start : Nat}
    (collision : NatTrajectoryRepeatedIndexCollision step start) :
    formedPositiveExcessOfIntersection
      (repeatedIndexIntersection
        (repeatedIndexCollision_of_trajectoryCollision collision)) =
        collision.secondTime + 1 :=
  rfl

/-- Public dynamic gap row generated by a repeated value in one trajectory. -/
def trajectoryDynamicGapRow
    {step : Nat -> Nat}
    {start : Nat}
    (collision : NatTrajectoryRepeatedIndexCollision step start) :
    ArithmeticDynamicGapRow :=
  repeatedIndexDynamicGapRow
    (repeatedIndexCollision_of_trajectoryCollision collision)

/-- Final trajectory row: dynamic gap plus recovered closed stability. -/
def trajectoryDynamicClosedStabilityRow
    {step : Nat -> Nat}
    {start : Nat}
    (collision : NatTrajectoryRepeatedIndexCollision step start) :
    ArithmeticDynamicClosedStabilityRow
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision collision)) where
  gapRow := trajectoryDynamicGapRow collision
  closedStability := trajectoryRepeatedIndexClosedStabilityInstance collision

/-! ## Window lock -/

/--
A finite-window collision has terminal excess at the absolute right time.
-/
theorem windowCollision_terminalExcess_eq
    {step : Nat -> Nat}
    {start windowStart windowLength : Nat}
    (collision :
      NatTrajectoryWindowCollision step start windowStart windowLength) :
    formedPositiveExcessOfIntersection
      (repeatedIndexIntersection
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision collision))) =
        windowStart + collision.rightOffset + 1 :=
  rfl

/-- Public dynamic gap row generated by a finite-window collision. -/
def windowCollisionDynamicGapRow
    {step : Nat -> Nat}
    {start windowStart windowLength : Nat}
    (collision :
      NatTrajectoryWindowCollision step start windowStart windowLength) :
    ArithmeticDynamicGapRow :=
  trajectoryDynamicGapRow
    (trajectoryCollision_of_windowCollision collision)

/-- Final window-collision row: dynamic gap plus recovered closed stability. -/
def windowCollisionDynamicClosedStabilityRow
    {step : Nat -> Nat}
    {start windowStart windowLength : Nat}
    (collision :
      NatTrajectoryWindowCollision step start windowStart windowLength) :
    ArithmeticDynamicClosedStabilityRow
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision collision))) where
  gapRow := windowCollisionDynamicGapRow collision
  closedStability := windowCollisionClosedStabilityInstance collision

/-- Public dynamic gap row constructively produced by a bounded window. -/
def boundedWindowDynamicGapRow
    {step : Nat -> Nat}
    {start windowStart B : Nat}
    (window : NatTrajectoryBoundedWindow step start windowStart B) :
    ArithmeticDynamicGapRow :=
  windowCollisionDynamicGapRow
    (windowCollision_of_boundedWindow window)

/-- Final bounded-window row: produced gap plus recovered closed stability. -/
def boundedWindowDynamicClosedStabilityRow
    {step : Nat -> Nat}
    {start windowStart B : Nat}
    (window : NatTrajectoryBoundedWindow step start windowStart B) :
    ArithmeticDynamicClosedStabilityRow
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (windowCollision_of_boundedWindow window)))) where
  gapRow := boundedWindowDynamicGapRow window
  closedStability := boundedWindowClosedStabilityInstance window

/-! ## Height and post-peak lock -/

/-- The canonical positive diagonal at height has terminal excess `1`. -/
theorem canonicalPositiveDiagonalTerminalExcess_eq_one
    (height : Nat) :
    formedPositiveExcessOfIntersection
      (canonicalIntersection height) = 1 :=
  rfl

/-- Public dynamic gap row generated from a post-peak finite-prefix window. -/
def postPeakWindowDynamicGapRow
    {step : Nat -> Nat}
    {start : Nat}
    {cert : NatTrajectoryFinitePrefixHeightCertificate step start}
    (window : NatTrajectoryPostPeakWindow cert) :
    ArithmeticDynamicGapRow :=
  boundedWindowDynamicGapRow
    (boundedWindow_of_postPeakWindow window)

/-- Final post-peak row: produced gap plus recovered closed stability. -/
def postPeakWindowDynamicClosedStabilityRow
    {step : Nat -> Nat}
    {start : Nat}
    {cert : NatTrajectoryFinitePrefixHeightCertificate step start}
    (window : NatTrajectoryPostPeakWindow cert) :
    ArithmeticDynamicClosedStabilityRow
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (windowCollision_of_boundedWindow
              (boundedWindow_of_postPeakWindow window))))) where
  gapRow := postPeakWindowDynamicGapRow window
  closedStability := postPeakWindowClosedStabilityInstance window

/-! ## Countdown lock -/

/-- The absolute right time of the countdown terminal collision is `n + 1`. -/
theorem countdownTerminalCollision_secondTime_eq
    (n : Nat) :
    (trajectoryCollision_of_windowCollision
      (countdownTerminalWindowCollision n)).secondTime = n + 1 :=
  Nat.zero_add (n + 1)

/-- The intrinsic countdown terminal dynamic excess is exactly `n + 2`. -/
theorem countdownTerminalExcess_eq_n_plus_two
    (n : Nat) :
    formedPositiveExcessOfIntersection
      (repeatedIndexIntersection
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (countdownTerminalWindowCollision n)))) =
        n + 2 := by
  change (0 + (n + 1)) + 1 = n + 2
  rw [Nat.zero_add, Nat.add_assoc]

/-- Public dynamic gap row generated by the explicit countdown terminal collision. -/
def countdownTerminalDynamicGapRow
    (n : Nat) :
    ArithmeticDynamicGapRow :=
  windowCollisionDynamicGapRow
    (countdownTerminalWindowCollision n)

/-- Final explicit countdown terminal row. -/
def countdownTerminalDynamicClosedStabilityRow
    (n : Nat) :
    ArithmeticDynamicClosedStabilityRow
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (countdownTerminalWindowCollision n)))) where
  gapRow := countdownTerminalDynamicGapRow n
  closedStability := countdownTerminalCollisionClosedStabilityInstance n

/--
The fully constructed countdown instance carries the same terminal dynamic gap
row as its explicit terminal collision.
-/
def fullyConstructedCountdownDynamicGapRow
    (n : Nat) :
    ArithmeticDynamicGapRow :=
  countdownTerminalDynamicGapRow n

/-- Final fully constructed countdown row. -/
def fullyConstructedCountdownDynamicClosedStabilityRow
    (n : Nat) :
    ArithmeticDynamicClosedStabilityRow
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (countdownTerminalWindowCollision n)))) where
  gapRow := fullyConstructedCountdownDynamicGapRow n
  closedStability := fullyConstructedEnrichedNatClosedStabilityInstance n

end EnrichedNatClosedStabilityInstance
end Clean
end Standalone
end LocalSemanticClosure

/- AXIOM_AUDIT_BEGIN -/
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.ArithmeticDynamicGapRow
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.ArithmeticDynamicClosedStabilityRow
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.arithmeticDynamicGapRowOfIntersection
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.repeatedIndexTerminalExcess_eq
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.repeatedIndexDynamicGapRow
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.repeatedIndexDynamicClosedStabilityRow
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.trajectoryCollision_terminalExcess_eq
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.trajectoryDynamicGapRow
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.trajectoryDynamicClosedStabilityRow
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.windowCollision_terminalExcess_eq
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.boundedWindowDynamicGapRow
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.windowCollisionDynamicClosedStabilityRow
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.boundedWindowDynamicClosedStabilityRow
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.canonicalPositiveDiagonalTerminalExcess_eq_one
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.postPeakWindowDynamicGapRow
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.postPeakWindowDynamicClosedStabilityRow
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.countdownTerminalCollision_secondTime_eq
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.countdownTerminalExcess_eq_n_plus_two
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.countdownTerminalDynamicGapRow
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.countdownTerminalDynamicClosedStabilityRow
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.fullyConstructedCountdownDynamicGapRow
#print axioms LocalSemanticClosure.Standalone.Clean.EnrichedNatClosedStabilityInstance.fullyConstructedCountdownDynamicClosedStabilityRow
/- AXIOM_AUDIT_END -/
