import Meta.AdaptiveRepairability.Synthesis

namespace Meta.AdaptiveRepairability

/-!
Canonical exact-posterior compilation and exactness of every leaf generated by
that compiler.
-/

structure ExactPosteriorRepairComplete (E : FinitePublicEnvironment) where
  realizeResponse :
    ∀ (s : E.actionModel.State)
      (g : E.actionModel.Obligation)
      (q : E.Query),
      E.authorized s g q →
      ∀ rr : RealizableResponse E s q,
        PublicRepairStep E s g q rr.1
  exactPosterior :
    ∀ (s : E.actionModel.State)
      (g : E.actionModel.Obligation)
      (q : E.Query)
      (authorization : E.authorized s g q)
      (rr : RealizableResponse E s q)
      (w : E.actionModel.World),
      Compatible E.actionModel
          (realizeResponse s g q authorization rr).after w ↔
        (Compatible E.actionModel s w ∧ E.respond w q = rr.1)

def GeneratedByExactCompiler
    {E : FinitePublicEnvironment}
    (complete : ExactPosteriorRepairComplete E)
    {s : E.actionModel.State}
    {g : E.actionModel.Obligation}
    (tree : PublicRepairTree E g s) : Prop :=
  match tree with
  | .stop => True
  | .ask q authorization step next =>
      (∀ rr, step rr = complete.realizeResponse s g q authorization rr) ∧
      (∀ rr, GeneratedByExactCompiler complete (next rr))

def ReachesLeaf
    {E : FinitePublicEnvironment}
    {s : E.actionModel.State}
    {g : E.actionModel.Obligation}
    (tree : PublicRepairTree E g s)
    (w : E.actionModel.World)
    (leaf : Leaf tree) : Prop :=
  match tree, leaf with
  | .stop, _ => Compatible E.actionModel s w
  | .ask q _authorization _step next, ⟨rr, tail⟩ =>
      Compatible E.actionModel s w ∧
      E.respond w q = rr.1 ∧
      ReachesLeaf (next rr) w tail

theorem exactGeneratedTree_leafPosterior
    {E : FinitePublicEnvironment}
    (complete : ExactPosteriorRepairComplete E)
    {s : E.actionModel.State}
    {g : E.actionModel.Obligation}
    (tree : PublicRepairTree E g s)
    (generated : GeneratedByExactCompiler complete tree)
    (leaf : Leaf tree)
    (w : E.actionModel.World) :
    Compatible E.actionModel (leafState tree leaf) w ↔
      ReachesLeaf tree w leaf := by
  induction tree with
  | stop =>
      cases leaf
      exact Iff.rfl
  | @ask state q authorization step next ih =>
      rcases leaf with ⟨rr, tail⟩
      have hstep :
          step rr = complete.realizeResponse state g q authorization rr :=
        generated.1 rr
      have htailGenerated := generated.2 rr
      have htailExact := ih rr htailGenerated tail
      constructor
      · intro hterminal
        have htailReach : ReachesLeaf (next rr) w tail :=
          htailExact.mp hterminal
        have hafter : Compatible E.actionModel (step rr).after w :=
          leaf_fiberIncluded (next rr) tail w hterminal
        have hcanonicalAfter :
            Compatible E.actionModel
              (complete.realizeResponse state g q authorization rr).after w := by
          rw [← hstep]
          exact hafter
        have hposterior :=
          (complete.exactPosterior state g q authorization rr w).mp hcanonicalAfter
        exact ⟨hposterior.1, hposterior.2, htailReach⟩
      · rintro ⟨hbefore, hresponse, htailReach⟩
        exact htailExact.mpr htailReach

structure ExactComposablePairSeparatingEpisode
    (E : FinitePublicEnvironment)
    (complete : ExactPosteriorRepairComplete E)
    (Invariant : E.actionModel.State → E.actionModel.Obligation → Prop)
    (s : E.actionModel.State)
    (g : E.actionModel.Obligation)
    (w₁ w₂ : E.actionModel.World) where
  composable : ComposablePairSeparatingEpisode E Invariant s g w₁ w₂
  generated : GeneratedByExactCompiler complete composable.episode

def ExactComposableAdaptivePairSeparability
    (E : FinitePublicEnvironment)
    (complete : ExactPosteriorRepairComplete E)
    (Invariant : E.actionModel.State → E.actionModel.Obligation → Prop)
    (g : E.actionModel.Obligation) : Type :=
  ∀ (s : E.actionModel.State),
    Invariant s g →
    ∀ w₁ w₂,
      ActionConflict E.actionModel s g w₁ w₂ →
      ExactComposablePairSeparatingEpisode
        E complete Invariant s g w₁ w₂

def forgetExactComposableSeparability
    {E : FinitePublicEnvironment}
    {complete : ExactPosteriorRepairComplete E}
    {Invariant : E.actionModel.State → E.actionModel.Obligation → Prop}
    {g : E.actionModel.Obligation}
    (exactSeparability :
      ExactComposableAdaptivePairSeparability E complete Invariant g) :
    ComposableAdaptivePairSeparability E Invariant g := by
  intro s hinvariant w₁ w₂ hconflict
  exact (exactSeparability s hinvariant w₁ w₂ hconflict).composable

theorem exactComposableSeparability_implies_certifiedRepairable
    {E : FinitePublicEnvironment}
    (D : PublicDecisionDoctrine E)
    (decisionComplete : DecisionRealizationComplete D)
    (complete : ExactPosteriorRepairComplete E)
    (Invariant : E.actionModel.State → E.actionModel.Obligation → Prop)
    (g : E.actionModel.Obligation)
    (exactSeparability :
      ExactComposableAdaptivePairSeparability E complete Invariant g)
    (s : E.actionModel.State)
    (hinvariant : Invariant s g)
    (hnonempty : PublicFiberNonempty E s) :
    CertifiedRepairableAt D s g :=
  composableSeparability_implies_certifiedRepairable
    D
    decisionComplete
    Invariant
    g
    (forgetExactComposableSeparability exactSeparability)
    s
    hinvariant
    hnonempty

/- AXIOM_AUDIT_BEGIN -/
#print axioms exactGeneratedTree_leafPosterior
#print axioms forgetExactComposableSeparability
#print axioms exactComposableSeparability_implies_certifiedRepairable
/- AXIOM_AUDIT_END -/
