import Meta.Core.CausalTotality

/-!
# Intrinsic causal finiteness and causal order without `Nat`

This module defines the finite type of positions preceding a causal word and
the prefix order generated by causal addition.  It also identifies this order
with reachability on every accumulating causal orbit and turns every positive
precedence into a constructive strict memory inclusion.

No standard natural number, finite ordinal, quotient, or classical principle
is used.
-/

namespace Meta
namespace CausalAdditive

/-! ## A finite type measured by a causal word -/

/-- Positions strictly preceding the endpoint of a causal word. -/
def CausalFin : CausalWord -> Type
  | CausalWord.zero => Empty
  | CausalWord.succ previous => Option (CausalFin previous)

namespace CausalWord.ConstructiveEquivalence

universe u v w

/-- The identity constructive equivalence. -/
def refl (Source : Type u) :
    CausalWord.ConstructiveEquivalence Source Source where
  toFun := fun source => source
  invFun := fun source => source
  left_inv := fun _ => rfl
  right_inv := fun _ => rfl

/-- Constructive equivalences lift through `Option`. -/
def option
    {Source : Type u}
    {Target : Type v}
    (equivalence :
      CausalWord.ConstructiveEquivalence Source Target) :
    CausalWord.ConstructiveEquivalence
      (Option Source)
      (Option Target) where
  toFun := fun source => Option.map equivalence.toFun source
  invFun := fun target => Option.map equivalence.invFun target
  left_inv := by
    intro source
    cases source with
    | none => rfl
    | some value =>
        exact congrArg Option.some (equivalence.left_inv value)
  right_inv := by
    intro target
    cases target with
    | none => rfl
    | some value =>
        exact congrArg Option.some (equivalence.right_inv value)

/-- Constructive equivalences compose without function extensionality. -/
def trans
    {First : Type u}
    {Second : Type v}
    {Third : Type w}
    (first : CausalWord.ConstructiveEquivalence First Second)
    (second : CausalWord.ConstructiveEquivalence Second Third) :
    CausalWord.ConstructiveEquivalence First Third where
  toFun := fun source => second.toFun (first.toFun source)
  invFun := fun target => first.invFun (second.invFun target)
  left_inv := by
    intro source
    rw [second.left_inv]
    exact first.left_inv source
  right_inv := by
    intro target
    rw [first.right_inv]
    exact second.right_inv target

end CausalWord.ConstructiveEquivalence

namespace CausalFin

/-- Reindexing a causal finite type along equality of its causal size. -/
def castEquivalence
    {left right : CausalWord}
    (same : left = right) :
    CausalWord.ConstructiveEquivalence
      (CausalFin left)
      (CausalFin right) := by
  cases same
  exact CausalWord.ConstructiveEquivalence.refl (CausalFin left)

end CausalFin

namespace CausalWord

/-! ## Prefix order generated by causal addition -/

/-- Positive data exhibiting a causal extension. -/
structure Extension (source target : CausalWord) : Type where
  suffix : CausalWord
  target_eq : target = CausalWord.add source suffix

/-- Positive data exhibiting a nonempty causal extension. -/
structure PositiveExtension (source target : CausalWord) : Type where
  suffix : CausalWord
  suffix_nonzero : suffix = CausalWord.zero -> False
  target_eq : target = CausalWord.add source suffix

/-- `source` causally precedes `target` when `target` is obtained by adding a
causal suffix. -/
def Precedes (source target : CausalWord) : Prop :=
  Exists fun suffix : CausalWord =>
    target = CausalWord.add source suffix

/-- Strict causal precedence carries an explicitly nonempty suffix. -/
def StrictlyPrecedes (source target : CausalWord) : Prop :=
  Exists fun suffix : CausalWord =>
    (suffix = CausalWord.zero -> False) ∧
      target = CausalWord.add source suffix

/-- Positive extension data entails propositional precedence. -/
theorem Extension.precedes
    {source target : CausalWord}
    (extension : Extension source target) :
    Precedes source target :=
  Exists.intro extension.suffix extension.target_eq

/-- Positive nonempty extension data entails strict precedence. -/
theorem PositiveExtension.strictlyPrecedes
    {source target : CausalWord}
    (extension : PositiveExtension source target) :
    StrictlyPrecedes source target :=
  Exists.intro
    extension.suffix
    (And.intro extension.suffix_nonzero extension.target_eq)

/-- If a causal sum is zero, its left summand is zero. -/
theorem left_eq_zero_of_add_eq_zero
    {left right : CausalWord}
    (same : CausalWord.add left right = CausalWord.zero) :
    left = CausalWord.zero := by
  cases right with
  | zero => exact same
  | succ previous =>
      exact (CausalWord.succ_ne_zero (CausalWord.add left previous) same).elim

/-- If a causal sum is zero, its right summand is zero. -/
theorem right_eq_zero_of_add_eq_zero
    {left right : CausalWord}
    (same : CausalWord.add left right = CausalWord.zero) :
    right = CausalWord.zero :=
  CausalWord.left_eq_zero_of_add_eq_zero
    ((CausalWord.add_commutative right left).trans same)

/-- Causal precedence is reflexive. -/
theorem precedes_reflexive (word : CausalWord) :
    Precedes word word :=
  Exists.intro CausalWord.zero rfl

/-- Causal precedence is transitive. -/
theorem precedes_transitive
    {first second third : CausalWord}
    (firstSecond : Precedes first second)
    (secondThird : Precedes second third) :
    Precedes first third := by
  cases firstSecond with
  | intro firstSuffix second_eq =>
      cases secondThird with
      | intro secondSuffix third_eq =>
          refine Exists.intro (CausalWord.add firstSuffix secondSuffix) ?_
          calc
            third = CausalWord.add second secondSuffix := third_eq
            _ = CausalWord.add
                  (CausalWord.add first firstSuffix)
                  secondSuffix :=
              congrArg
                (fun word => CausalWord.add word secondSuffix)
                second_eq
            _ = CausalWord.add
                  first
                  (CausalWord.add firstSuffix secondSuffix) :=
              CausalWord.add_associative
                first firstSuffix secondSuffix

/-- Causal precedence is antisymmetric. -/
theorem precedes_antisymmetric
    {left right : CausalWord}
    (leftRight : Precedes left right)
    (rightLeft : Precedes right left) :
    left = right := by
  cases leftRight with
  | intro forwardSuffix right_eq =>
      cases rightLeft with
      | intro backwardSuffix left_eq =>
          have absorbed :
              CausalWord.add
                  left
                  (CausalWord.add forwardSuffix backwardSuffix) =
                left := by
            calc
              CausalWord.add
                    left
                    (CausalWord.add forwardSuffix backwardSuffix) =
                  CausalWord.add
                    (CausalWord.add left forwardSuffix)
                    backwardSuffix :=
                (CausalWord.add_associative
                  left forwardSuffix backwardSuffix).symm
              _ = CausalWord.add right backwardSuffix :=
                congrArg
                  (fun word => CausalWord.add word backwardSuffix)
                  right_eq.symm
              _ = left := left_eq.symm
          have suffixesZero :
              CausalWord.add forwardSuffix backwardSuffix =
                CausalWord.zero :=
            CausalWord.add_eq_left_implies_zero absorbed
          have forwardZero :
              forwardSuffix = CausalWord.zero :=
            CausalWord.left_eq_zero_of_add_eq_zero suffixesZero
          calc
            left = CausalWord.add left CausalWord.zero := rfl
            _ = CausalWord.add left forwardSuffix :=
              congrArg (CausalWord.add left) forwardZero.symm
            _ = right := right_eq.symm

/-- No causal word strictly precedes itself. -/
theorem strictlyPrecedes_irreflexive
    (word : CausalWord)
    (strict : StrictlyPrecedes word word) :
    False := by
  cases strict with
  | intro suffix data =>
      exact
        data.1
          (CausalWord.add_eq_left_implies_zero data.2.symm)

/-- Any two unary causal words are comparable by causal precedence. -/
def precedenceComparable
    (left right : CausalWord) :
    Sum (Extension left right) (Extension right left) :=
  match CausalWord.compare left right with
  | PrefixComparison.equal same =>
      Sum.inl (by
        cases same
        exact {
          suffix := CausalWord.zero
          target_eq := rfl
        })
  | PrefixComparison.leftPrefix suffix _ right_eq =>
      Sum.inl {
        suffix := suffix
        target_eq := right_eq
      }
  | PrefixComparison.rightPrefix suffix _ left_eq =>
      Sum.inr {
        suffix := suffix
        target_eq := left_eq
      }

end CausalWord

/-! ## Reachability and strict memory growth -/

namespace AccumulatingCausalSystem

universe u v

variable {State : Type u}
variable {Gap : Type v}

/-- Reachability by a finite causal word. -/
def Reachable
    (system : AccumulatingCausalSystem State Gap)
    (source target : State) :
    Prop :=
  Exists fun word : CausalWord =>
    target = system.eval source word

/-- Reachability is reflexive. -/
theorem reachable_reflexive
    (system : AccumulatingCausalSystem State Gap)
    (state : State) :
    system.Reachable state state :=
  Exists.intro CausalWord.zero rfl

/-- Reachability is transitive by causal addition. -/
theorem reachable_transitive
    (system : AccumulatingCausalSystem State Gap)
    {first second third : State}
    (firstSecond : system.Reachable first second)
    (secondThird : system.Reachable second third) :
    system.Reachable first third := by
  cases firstSecond with
  | intro firstWord second_eq =>
      cases secondThird with
      | intro secondWord third_eq =>
          refine Exists.intro (CausalWord.add firstWord secondWord) ?_
          calc
            third = system.eval second secondWord := third_eq
            _ = system.eval (system.eval first firstWord) secondWord :=
              congrArg
                (fun state => system.eval state secondWord)
                second_eq
            _ = system.eval
                  first
                  (CausalWord.add firstWord secondWord) :=
              (system.eval_add first firstWord secondWord).symm

/-- Memory preservation along an arbitrary causal word. -/
theorem memory_preserved_eval
    (system : AccumulatingCausalSystem State Gap)
    (state : State)
    (word : CausalWord)
    (rememberedGap : Gap)
    (remembered : system.Memory state rememberedGap) :
    system.Memory (system.eval state word) rememberedGap := by
  induction word with
  | zero => exact remembered
  | succ previous inductionHypothesis =>
      exact
        system.memory_preserved
          (system.eval state previous)
          rememberedGap
          inductionHypothesis

/-- On a faithful accumulating orbit, reachability is exactly causal-word
precedence. -/
theorem orbitReachable_iff_precedes
    (system : AccumulatingCausalSystem State Gap)
    (initial : State)
    (source target : CausalWord) :
    system.Reachable
        (system.eval initial source)
        (system.eval initial target) ↔
      CausalWord.Precedes source target := by
  constructor
  · intro reachable
    cases reachable with
    | intro suffix target_eq =>
        refine Exists.intro suffix ?_
        apply system.eval_injective initial
        calc
          system.eval initial target =
              system.eval (system.eval initial source) suffix :=
            target_eq
          _ = system.eval
                initial
                (CausalWord.add source suffix) :=
            (system.eval_add initial source suffix).symm
  · intro precedes
    cases precedes with
    | intro suffix target_eq =>
        refine Exists.intro suffix ?_
        calc
          system.eval initial target =
              system.eval
                initial
                (CausalWord.add source suffix) :=
            congrArg (system.eval initial) target_eq
          _ = system.eval (system.eval initial source) suffix :=
            system.eval_add initial source suffix

/-- A positive causal prefix relation is realized as a constructive strict
memory inclusion. -/
def positiveExtension_strictMemoryInclusion
    (system : AccumulatingCausalSystem State Gap)
    (initial : State)
    {source target : CausalWord}
    (extension : CausalWord.PositiveExtension source target) :
    StrictPredicateInclusion
      (system.Memory (system.eval initial source))
      (system.Memory (system.eval initial target)) := by
      have targetEvaluation :
          system.eval initial target =
            system.eval
              (system.eval initial source)
              extension.suffix := by
        calc
          system.eval initial target =
              system.eval
                initial
                (CausalWord.add source extension.suffix) :=
            congrArg (system.eval initial) extension.target_eq
          _ = system.eval
                (system.eval initial source)
                extension.suffix :=
            system.eval_add initial source extension.suffix
      exact {
        included := by
          intro rememberedGap remembered
          rw [targetEvaluation]
          exact
            system.memory_preserved_eval
              (system.eval initial source)
              extension.suffix
              rememberedGap
              remembered
        witness := system.gap (system.eval initial source)
        witness_absent := system.gap_absent (system.eval initial source)
        witness_present := by
          rw [targetEvaluation]
          exact
            system.remembers_source_gap_of_nonzero
              (system.eval initial source)
              extension.suffix
              extension.suffix_nonzero
      }

end AccumulatingCausalSystem
end CausalAdditive
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.CausalAdditive.CausalFin
#print axioms Meta.CausalAdditive.CausalWord.precedes_antisymmetric
#print axioms Meta.CausalAdditive.CausalWord.strictlyPrecedes_irreflexive
#print axioms Meta.CausalAdditive.AccumulatingCausalSystem.orbitReachable_iff_precedes
#print axioms Meta.CausalAdditive.AccumulatingCausalSystem.positiveExtension_strictMemoryInclusion
/- AXIOM_AUDIT_END -/
