import Meta.Core.Parity

/-!
# Compatibility facade for dynamic parity separation

Import `Meta.Core.Parity` in new code.
-/

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.ClosedStabilityTheorem.DynamicParitySeparation
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_dynamicOperationalTwoPole
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_parityOperationalTwoPole
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_dynamicStructuralTwoPole
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_parityStructuralTwoPole
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_roleCarrier
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_formedRegime
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_shadowRegime
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_formedVisible
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_shadowVisible
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_formedRegime_eq_leftPole
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_shadowRegime_eq_rightPole
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_formedVisible_eq_projection
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_shadowVisible_eq_projection
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_sameParityVisible
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_separatedParityRegimes
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_refutesParityShortPresentation
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_parityNotContractible
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_noParityProjectiveReconstruction
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_leftRight
#print axioms Meta.ClosedStabilityTheorem.dynamicParitySeparation_rightLeft
#print axioms Meta.ClosedStabilityTheorem.OperationalParityRoles
#print axioms Meta.ClosedStabilityTheorem.operationalParityRolesOfDynamicParitySeparation
#print axioms Meta.ClosedStabilityTheorem.operationalParityRoles_mediatedDynamicRoles
#print axioms Meta.ClosedStabilityTheorem.operationalParityRoles_closingRegime
#print axioms Meta.ClosedStabilityTheorem.operationalParityRoles_mediatingRegime
#print axioms Meta.ClosedStabilityTheorem.operationalParityRoles_closing_eq_formed
#print axioms Meta.ClosedStabilityTheorem.operationalParityRoles_mediating_eq_shadow
#print axioms Meta.ClosedStabilityTheorem.operationalParityRoles_sameVisible
#print axioms Meta.ClosedStabilityTheorem.operationalParityRoles_separated
#print axioms Meta.ClosedStabilityTheorem.operationalParityRoles_dynamicRepair
#print axioms Meta.ClosedStabilityTheorem.operationalParityRoles_noParityVisibleReconstruction
#print axioms Meta.ClosedStabilityTheorem.operationalParityRoles_sameParityProjection
#print axioms Meta.ClosedStabilityTheorem.operationalParityRoles_refutesParityShortPresentation
#print axioms Meta.ClosedStabilityTheorem.operationalParityRoles_parityNotContractible
#print axioms Meta.ClosedStabilityTheorem.operationalParityRoles_leftRight
#print axioms Meta.ClosedStabilityTheorem.operationalParityRoles_rightLeft
/- AXIOM_AUDIT_END -/
