import Meta.Core.TransportCoherence

/-!
# Nontrivial three-phase transport model

This model validates composition with two consecutive non-reflexive uses.  Use
witnesses and transport witnesses are distinct inductive families, and the
transport map preserves their composition.
-/

namespace Meta
namespace TransportCoherenceModel

open RelaxedUsageRegime

/-- Three distinct stages of one route. -/
inductive ThreePhase where
  | before
  | during
  | after

/-- Proof-relevant directed uses between the three stages. -/
inductive ThreePhaseUse : ThreePhase -> ThreePhase -> Type where
  | reflBefore : ThreePhaseUse ThreePhase.before ThreePhase.before
  | reflDuring : ThreePhaseUse ThreePhase.during ThreePhase.during
  | reflAfter : ThreePhaseUse ThreePhase.after ThreePhase.after
  | enter : ThreePhaseUse ThreePhase.before ThreePhase.during
  | finish : ThreePhaseUse ThreePhase.during ThreePhase.after
  | traverse : ThreePhaseUse ThreePhase.before ThreePhase.after

/-- Composition includes the substantial `enter ; finish = traverse` case. -/
def ThreePhaseUse.compose
    {x y z : ThreePhase}
    (first : ThreePhaseUse x y)
    (second : ThreePhaseUse y z) :
    ThreePhaseUse x z := by
  cases first with
  | reflBefore => exact second
  | reflDuring => exact second
  | reflAfter => exact second
  | enter =>
      cases second with
      | reflDuring => exact ThreePhaseUse.enter
      | finish => exact ThreePhaseUse.traverse
  | finish =>
      cases second with
      | reflAfter => exact ThreePhaseUse.finish
  | traverse =>
      cases second with
      | reflAfter => exact ThreePhaseUse.traverse

/-- Output transports are not definitionally the use witnesses. -/
inductive ThreePhaseTransport : ThreePhase -> ThreePhase -> Type where
  | stayBefore : ThreePhaseTransport ThreePhase.before ThreePhase.before
  | stayDuring : ThreePhaseTransport ThreePhase.during ThreePhase.during
  | stayAfter : ThreePhaseTransport ThreePhase.after ThreePhase.after
  | entered : ThreePhaseTransport ThreePhase.before ThreePhase.during
  | finished : ThreePhaseTransport ThreePhase.during ThreePhase.after
  | traversed : ThreePhaseTransport ThreePhase.before ThreePhase.after

/-- Lawful composition of output transports. -/
def ThreePhaseTransport.compose
    {x y z : ThreePhase}
    (first : ThreePhaseTransport x y)
    (second : ThreePhaseTransport y z) :
    ThreePhaseTransport x z := by
  cases first with
  | stayBefore => exact second
  | stayDuring => exact second
  | stayAfter => exact second
  | entered =>
      cases second with
      | stayDuring => exact ThreePhaseTransport.entered
      | finished => exact ThreePhaseTransport.traversed
  | finished =>
      cases second with
      | stayAfter => exact ThreePhaseTransport.finished
  | traversed =>
      cases second with
      | stayAfter => exact ThreePhaseTransport.traversed

/-- The concrete transport generated by each authorized use. -/
def threePhaseTransportOfUse
    {x y : ThreePhase}
    (use : ThreePhaseUse x y) :
    ThreePhaseTransport x y := by
  cases use with
  | reflBefore => exact ThreePhaseTransport.stayBefore
  | reflDuring => exact ThreePhaseTransport.stayDuring
  | reflAfter => exact ThreePhaseTransport.stayAfter
  | enter => exact ThreePhaseTransport.entered
  | finish => exact ThreePhaseTransport.finished
  | traverse => exact ThreePhaseTransport.traversed

/-- The use-to-transport map preserves every composable pair. -/
theorem threePhaseTransportOfUse_compose
    {x y z : ThreePhase}
    (first : ThreePhaseUse x y)
    (second : ThreePhaseUse y z) :
    threePhaseTransportOfUse (first.compose second) =
      (threePhaseTransportOfUse first).compose
        (threePhaseTransportOfUse second) := by
  cases first <;> cases second <;> rfl

/-- The model has an explicit nonempty context rather than a `Unit` alias. -/
inductive ThreePhaseContext where
  | route

/-- The route reading exposes the current phase. -/
inductive ThreePhaseReading : ThreePhaseContext -> Type where
  | stage : ThreePhaseReading ThreePhaseContext.route

/-- The first and last stages are constructively distinct. -/
theorem threePhase_before_ne_after :
    ThreePhase.before = ThreePhase.after -> False := by
  intro equality
  cases equality

/-- A relaxed regime whose output transport is distinct from its use family. -/
def threePhaseRegime : RelaxedInterfaceRegime ThreePhase where
  Ctx := ThreePhaseContext
  defaultCtx := ThreePhaseContext.route
  Read := ThreePhaseReading
  defaultRead := fun context => by
    cases context
    exact ThreePhaseReading.stage
  Out := fun _ _ => ThreePhase
  read := fun _ _ phase => phase
  Sep := fun _ left right => PLift (left = right -> False)
  Coord := fun _ left right => ThreePhaseUse left right
  Use := fun _ left right => ThreePhaseUse left right
  OutRel := fun _ _ left right => ThreePhaseTransport left right
  use_of_noncontractive := fun _ coordination => coordination
  transport := fun use _ => threePhaseTransportOfUse use

/-- Intrinsic identities and composition of three-phase uses. -/
def threePhaseCompositionalUse :
    CompositionalUse threePhaseRegime where
  identity := by
    intro context phase
    cases phase with
    | before => exact ThreePhaseUse.reflBefore
    | during => exact ThreePhaseUse.reflDuring
    | after => exact ThreePhaseUse.reflAfter
  compose := fun first second => first.compose second

/-- The use composition operations satisfy all three laws. -/
def threePhaseLawfulCompositionalUse :
    LawfulCompositionalUse
      threePhaseRegime
      threePhaseCompositionalUse where
  leftIdentity := by
    intro context x y use
    cases use <;> rfl
  rightIdentity := by
    intro context x y use
    cases use <;> rfl
  associativity := by
    intro context w x y z first second third
    cases first <;> cases second <;> cases third <;> rfl

/-- The complete coherent transport structure of the model. -/
def threePhaseCompositionalTransport :
    CompositionalTransport
      threePhaseRegime
      threePhaseCompositionalUse where
  useLaws := threePhaseLawfulCompositionalUse
  outIdentity := by
    intro context reading phase
    cases phase with
    | before => exact ThreePhaseTransport.stayBefore
    | during => exact ThreePhaseTransport.stayDuring
    | after => exact ThreePhaseTransport.stayAfter
  outCompose := by
    intro context reading x y z first second
    exact first.compose second
  outLeftIdentity := by
    intro context reading x y relation
    cases relation <;> rfl
  outRightIdentity := by
    intro context reading x y relation
    cases relation <;> rfl
  outAssociativity := by
    intro context reading w x y z first second third
    cases first <;> cases second <;> cases third <;> rfl
  transportIdentity := by
    intro context reading phase
    cases phase <;> rfl
  transportComposition := by
    intro context reading x y z first second
    exact threePhaseTransportOfUse_compose first second

/-- First non-reflexive use. -/
def threePhase_enterUse :
    threePhaseRegime.Use
      ThreePhaseContext.route
      ThreePhase.before
      ThreePhase.during :=
  ThreePhaseUse.enter

/-- Second non-reflexive use. -/
def threePhase_finishUse :
    threePhaseRegime.Use
      ThreePhaseContext.route
      ThreePhase.during
      ThreePhase.after :=
  ThreePhaseUse.finish

/-- The two non-reflexive uses compose to the direct use. -/
theorem threePhase_enter_finish_compose :
    threePhaseCompositionalUse.compose
      threePhase_enterUse
      threePhase_finishUse =
        ThreePhaseUse.traverse :=
  rfl

/-- Their two transports compose to the direct substantial transport. -/
theorem threePhase_enter_finish_transport_compose :
    threePhaseCompositionalTransport.outCompose
      ThreePhaseReading.stage
      (threePhaseRegime.transport
        threePhase_enterUse
        ThreePhaseReading.stage)
      (threePhaseRegime.transport
        threePhase_finishUse
        ThreePhaseReading.stage) =
      ThreePhaseTransport.traversed :=
  rfl

/-- The functoriality law identifies direct and two-step transport. -/
theorem threePhase_direct_transport_eq_composed :
    threePhaseRegime.transport
        (threePhaseCompositionalUse.compose
          threePhase_enterUse
          threePhase_finishUse)
        ThreePhaseReading.stage =
      threePhaseCompositionalTransport.outCompose
        ThreePhaseReading.stage
        (threePhaseRegime.transport
          threePhase_enterUse
          ThreePhaseReading.stage)
        (threePhaseRegime.transport
          threePhase_finishUse
          ThreePhaseReading.stage) :=
  threePhaseCompositionalTransport.transportComposition
    ThreePhaseReading.stage
    threePhase_enterUse
    threePhase_finishUse

end TransportCoherenceModel
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.TransportCoherenceModel.ThreePhaseUse
#print axioms Meta.TransportCoherenceModel.ThreePhaseTransport
#print axioms Meta.TransportCoherenceModel.threePhaseTransportOfUse_compose
#print axioms Meta.TransportCoherenceModel.threePhaseRegime
#print axioms Meta.TransportCoherenceModel.threePhaseCompositionalTransport
#print axioms Meta.TransportCoherenceModel.threePhase_enter_finish_compose
#print axioms Meta.TransportCoherenceModel.threePhase_direct_transport_eq_composed
/- AXIOM_AUDIT_END -/
