import Meta.Core.DynamicStability
import Meta.Arithmetic.Core

/-!
# Oriented arithmetic intersection poles

This file builds the oriented formed/shadow arithmetic interface generated by
one exact arithmetic intersection.
-/

namespace Meta
namespace EnrichedNatClosedStabilityInstance

open ClosedStabilityTheorem

/-! ## Oriented arithmetic interface generated by an intersection -/

/--
The oriented arithmetic interface generated by an exact arithmetic
intersection.

This is the non-trivial interface used for the parity instance: the role is
carried by the intersection itself, not recovered by classifying raw traces.
-/
inductive ArithmeticIntersectionPole
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) where
  | formed
  | shadow

/-- The trace carried by an oriented arithmetic pole. -/
def arithmeticIntersectionPoleTrace
    {branch : MemoryBranch}
    {intersection : PrimitiveMemoryReadingIntersection branch} :
    ArithmeticIntersectionPole intersection -> List NatTraceAtom
  | ArithmeticIntersectionPole.formed => formedTraceOfIntersection intersection
  | ArithmeticIntersectionPole.shadow => payloadOnlyTraceOfIntersection intersection

/-- The visible payload carried by an oriented arithmetic pole. -/
def arithmeticIntersectionPoleVisible
    {branch : MemoryBranch}
    {intersection : PrimitiveMemoryReadingIntersection branch}
    (pole : ArithmeticIntersectionPole intersection) :
    List Nat :=
  tracePayloads (arithmeticIntersectionPoleTrace pole)

/-- Repair type attached to the trace carried by an oriented arithmetic pole. -/
def arithmeticIntersectionPoleRepair
    {branch : MemoryBranch}
    {intersection : PrimitiveMemoryReadingIntersection branch}
    (pole : ArithmeticIntersectionPole intersection) :
    Type :=
  NatInterfaceRepair (arithmeticIntersectionPoleTrace pole)

/-- The formed arithmetic pole carries the formed intersection trace. -/
theorem arithmeticIntersectionPoleTrace_formed
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    arithmeticIntersectionPoleTrace
        (ArithmeticIntersectionPole.formed
          (intersection := intersection)) =
      formedTraceOfIntersection intersection :=
  rfl

/-- The shadow arithmetic pole carries the payload-only shadow trace. -/
theorem arithmeticIntersectionPoleTrace_shadow
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    arithmeticIntersectionPoleTrace
        (ArithmeticIntersectionPole.shadow
          (intersection := intersection)) =
      payloadOnlyTraceOfIntersection intersection :=
  rfl

/-- The formed and shadow arithmetic poles expose the same visible payload. -/
theorem arithmeticIntersectionPoleVisible_same
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    arithmeticIntersectionPoleVisible
        (ArithmeticIntersectionPole.formed
          (intersection := intersection)) =
      arithmeticIntersectionPoleVisible
        (ArithmeticIntersectionPole.shadow
          (intersection := intersection)) :=
  formedTraceOfIntersection_same_payloadOnlyPayload intersection

/-- The traces carried by the formed and shadow arithmetic poles remain separated. -/
theorem arithmeticIntersectionPoleTrace_separated
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    arithmeticIntersectionPoleTrace
        (ArithmeticIntersectionPole.formed
          (intersection := intersection)) =
      arithmeticIntersectionPoleTrace
        (ArithmeticIntersectionPole.shadow
          (intersection := intersection)) ->
        False :=
  formedTraceOfIntersection_ne_payloadOnlyTrace intersection

/-- The oriented formed and shadow arithmetic poles are separated. -/
theorem arithmeticIntersectionPole_separated
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    ArithmeticIntersectionPole.formed (intersection := intersection) =
      ArithmeticIntersectionPole.shadow (intersection := intersection) ->
        False := by
  intro h
  cases h

/--
The exact local recovery carried by the oriented arithmetic interface.

The same visible payload and the separation of the two traces are inherited
from the arithmetic intersection.
-/
def arithmeticIntersectionLocalRecovery
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    LocalProjectiveRecovery
      (ArithmeticIntersectionPole intersection)
      (List Nat)
      arithmeticIntersectionPoleVisible
      arithmeticIntersectionPoleRepair where
  formed := ArithmeticIntersectionPole.formed
  shadow := ArithmeticIntersectionPole.shadow
  sameProjection := arithmeticIntersectionPoleVisible_same intersection
  separated := arithmeticIntersectionPole_separated intersection
  repair := natInterfaceRepairOfIntersection intersection
  recovered := ArithmeticIntersectionPole.formed
  recovered_eq_formed := rfl

/-- Witness type for the trace carried by an oriented arithmetic pole. -/
def arithmeticIntersectionPoleWitness
    {branch : MemoryBranch}
    {intersection : PrimitiveMemoryReadingIntersection branch}
    (pole : ArithmeticIntersectionPole intersection) :
    Type :=
  NatInterfaceWitness (arithmeticIntersectionPoleTrace pole)

/-- Realization type for the trace carried by an oriented arithmetic pole. -/
def arithmeticIntersectionPoleRealization
    {branch : MemoryBranch}
    {intersection : PrimitiveMemoryReadingIntersection branch}
    (cycle :
      StrongTerminalCycleFromIntersection bidirectionalCompleteness branch)
    (pole : ArithmeticIntersectionPole intersection) :
    Type :=
  NatInterfaceRealization cycle (arithmeticIntersectionPoleTrace pole)

/-- The locally recovered dynamic return generated by one arithmetic intersection. -/
def arithmeticIntersectionDynamicReturn
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    LocallyRecoveredDynamicReturn
      bidirectionalCompleteness
      enrichedNatRoundTripCoherence
      branch
      PUnit
      (ArithmeticIntersectionPole intersection)
      arithmeticIntersectionPoleWitness
      arithmeticIntersectionPoleRealization
      (List Nat)
      arithmeticIntersectionPoleVisible
      arithmeticIntersectionPoleRepair where
  formedReturn :=
    { source := PUnit.unit
      intersection := intersection }
  formed :=
    { interface := ArithmeticIntersectionPole.formed
      witness :=
        { payload := tracePayloads (formedTraceOfIntersection intersection)
          payload_eq := rfl } }
  realizes :=
    { interface_eq_formedTrace := rfl }
  localRecovery := arithmeticIntersectionLocalRecovery intersection
  localRecovery_sameInterface := rfl

end EnrichedNatClosedStabilityInstance
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.EnrichedNatClosedStabilityInstance.ArithmeticIntersectionPole
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleTrace
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleVisible
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleRepair
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleTrace_formed
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleTrace_shadow
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleVisible_same
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleTrace_separated
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPole_separated
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionLocalRecovery
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleWitness
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleRealization
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionDynamicReturn
/- AXIOM_AUDIT_END -/
