import Meta.Arithmetic.DynamicParityInstance
import Meta.Arithmetic.CountdownDynamicGap

/-!
# Countdown arithmetic parity

This file specializes the arithmetic dynamic parity instance to the countdown
terminal closure.
-/

namespace Meta
namespace EnrichedNatClosedStabilityInstance

open ClosedStabilityTheorem

/-! ## Countdown specialization -/

/-- The arithmetic intersection generated by the terminal countdown collision. -/
def countdownArithmeticParityIntersection
    (n : Nat) :
    PrimitiveMemoryReadingIntersection
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (countdownTerminalWindowCollision n)))) :=
  repeatedIndexIntersection
    (repeatedIndexCollision_of_trajectoryCollision
      (trajectoryCollision_of_windowCollision
        (countdownTerminalWindowCollision n)))

/-- The countdown arithmetic parity dynamic return. -/
def countdownArithmeticParityDynamicReturn
    (n : Nat) :
    LocallyRecoveredDynamicReturn
      bidirectionalCompleteness
      enrichedNatRoundTripCoherence
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (countdownTerminalWindowCollision n))))
      PUnit
      (ArithmeticIntersectionPole (countdownArithmeticParityIntersection n))
      arithmeticIntersectionPoleWitness
      arithmeticIntersectionPoleRealization
      (List Nat)
      arithmeticIntersectionPoleVisible
      arithmeticIntersectionPoleRepair :=
  arithmeticIntersectionDynamicReturn
    (countdownArithmeticParityIntersection n)

/-- The countdown arithmetic parity raccord. -/
def countdownArithmeticParityRaccord
    (n : Nat) :
    DynamicParitySeparation
      (countdownArithmeticParityDynamicReturn n) :=
  arithmeticIntersectionParityRaccord
    (countdownArithmeticParityIntersection n)

/-- Operational parity roles generated by the countdown terminal closure. -/
def countdownOperationalParityRoles
    (n : Nat) :
    OperationalParityRoles
      (countdownArithmeticParityRaccord n) :=
  arithmeticIntersectionOperationalParityRoles
    (countdownArithmeticParityIntersection n)

/-- Arithmetic parity roles generated by the countdown terminal closure. -/
def countdownArithmeticParityRoles
    (n : Nat) :
    ArithmeticParityRoles
      (countdownOperationalParityRoles n) :=
  arithmeticIntersectionArithmeticParityRoles
    (countdownArithmeticParityIntersection n)

/-- The countdown terminal closure carries the arithmetic dynamic parity instance. -/
def countdownArithmeticParityInstance
    (n : Nat) :
    ArithmeticDynamicParityInstance
      (countdownArithmeticParityIntersection n) where
  dynamicReturn := countdownArithmeticParityDynamicReturn n
  parityRaccord := countdownArithmeticParityRaccord n
  operationalRoles := countdownOperationalParityRoles n
  arithmeticRoles := countdownArithmeticParityRoles n

/-- The countdown arithmetic parity instance keeps the terminal `n + 2` excess. -/
theorem countdownArithmeticParity_terminalExcess_eq_n_plus_two
    (n : Nat) :
    formedPositiveExcessOfIntersection
      (countdownArithmeticParityIntersection n) =
        n + 2 :=
  countdownTerminalExcess_eq_n_plus_two n

/-- Countdown arithmetic parity packaged together with its terminal excess lock. -/
structure CountdownArithmeticParityPackage
    (n : Nat) where
  parityInstance :
    ArithmeticDynamicParityInstance
      (countdownArithmeticParityIntersection n)
  terminalExcess_eq_n_plus_two :
    formedPositiveExcessOfIntersection
      (countdownArithmeticParityIntersection n) =
        n + 2

/-- Canonical countdown arithmetic parity package. -/
def countdownArithmeticParityPackage
    (n : Nat) :
    CountdownArithmeticParityPackage n where
  parityInstance := countdownArithmeticParityInstance n
  terminalExcess_eq_n_plus_two :=
    countdownArithmeticParity_terminalExcess_eq_n_plus_two n

/-- Countdown even and odd roles have the same parity visible. -/
theorem countdownArithmeticParity_sameParityProjection
    (n : Nat) :
    parityProjection
        (arithmeticParityRoles_evenRegime
          (countdownArithmeticParityRoles n)) =
      parityProjection
        (arithmeticParityRoles_oddRegime
          (countdownArithmeticParityRoles n)) :=
  arithmeticParityRoles_sameParityProjection
    (countdownArithmeticParityRoles n)

/-- Countdown even and odd roles remain separated. -/
theorem countdownArithmeticParity_separated
    (n : Nat) :
    arithmeticParityRoles_evenRegime
        (countdownArithmeticParityRoles n) =
      arithmeticParityRoles_oddRegime
        (countdownArithmeticParityRoles n) -> False :=
  arithmeticParityRoles_separated
    (countdownArithmeticParityRoles n)

/-- Countdown arithmetic parity rules out global parity-visible reconstruction. -/
def countdownArithmeticParity_noParityVisibleReconstruction
    (n : Nat) :
    ((recover : ParityVisible -> ParityRegime) ->
      ((regime : ParityRegime) ->
        recover (parityProjection regime) = regime) ->
      False) :=
  arithmeticDynamicParityInstance_noParityVisibleReconstruction
    (countdownArithmeticParityInstance n)

end EnrichedNatClosedStabilityInstance
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParityIntersection
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParityDynamicReturn
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParityRaccord
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownOperationalParityRoles
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParityRoles
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParityInstance
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParity_terminalExcess_eq_n_plus_two
#print axioms Meta.EnrichedNatClosedStabilityInstance.CountdownArithmeticParityPackage
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParityPackage
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParity_sameParityProjection
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParity_separated
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParity_noParityVisibleReconstruction
/- AXIOM_AUDIT_END -/
