import Meta.Arithmetic.DynamicGap
import Meta.Arithmetic.Countdown

/-!
# Countdown dynamic gap

This file contains the countdown-specific terminal dynamic gap rows.  The
generic arithmetic dynamic gap layer remains independent of the countdown
instance.
-/

namespace Meta
namespace EnrichedNatClosedStabilityInstance

open ClosedStabilityTheorem

/-! ## Countdown lock -/

/-- The absolute right time of the countdown terminal collision is `n + 1`. -/
theorem countdownTerminalCollision_secondTime_eq
    (n : Nat) :
    (trajectoryCollision_of_windowCollision
      (countdownTerminalWindowCollision n)).secondTime = n + 1 :=
  Nat.zero_add (n + 1)

/-- The intrinsic countdown terminal dynamic excess is exactly `n + 2`. -/
theorem countdownTerminalExcess_eq_n_plus_two
    (n : Nat) :
    formedPositiveExcessOfIntersection
      (repeatedIndexIntersection
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (countdownTerminalWindowCollision n)))) =
        n + 2 := by
  change (0 + (n + 1)) + 1 = n + 2
  rw [Nat.zero_add, Nat.add_assoc]

/-- Public dynamic gap row generated by the explicit countdown terminal collision. -/
def countdownTerminalDynamicGapRow
    (n : Nat) :
    ArithmeticDynamicGapRow :=
  windowCollisionDynamicGapRow
    (countdownTerminalWindowCollision n)

/-- Final explicit countdown terminal row. -/
def countdownTerminalDynamicClosedStabilityRow
    (n : Nat) :
    ArithmeticDynamicClosedStabilityRow
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (countdownTerminalWindowCollision n)))) where
  gapRow := countdownTerminalDynamicGapRow n
  closedStability := countdownTerminalCollisionClosedStabilityInstance n

/--
The fully constructed countdown instance carries the same terminal dynamic gap
row as its explicit terminal collision.
-/
def fullyConstructedCountdownDynamicGapRow
    (n : Nat) :
    ArithmeticDynamicGapRow :=
  countdownTerminalDynamicGapRow n

/-- Final fully constructed countdown row. -/
def fullyConstructedCountdownDynamicClosedStabilityRow
    (n : Nat) :
    ArithmeticDynamicClosedStabilityRow
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (countdownTerminalWindowCollision n)))) where
  gapRow := fullyConstructedCountdownDynamicGapRow n
  closedStability := fullyConstructedEnrichedNatClosedStabilityInstance n

end EnrichedNatClosedStabilityInstance
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalCollision_secondTime_eq
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalExcess_eq_n_plus_two
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalDynamicGapRow
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalDynamicClosedStabilityRow
#print axioms Meta.EnrichedNatClosedStabilityInstance.fullyConstructedCountdownDynamicGapRow
#print axioms Meta.EnrichedNatClosedStabilityInstance.fullyConstructedCountdownDynamicClosedStabilityRow
/- AXIOM_AUDIT_END -/
