import Meta.Arithmetic.HeightDiagonal

/-!
# Countdown
-/

namespace Meta
namespace EnrichedNatClosedStabilityInstance

open ClosedStabilityTheorem

/-! ## Intrinsic countdown instance -/

/-- A strictly internal Nat dynamics: positive values count down, zero is terminal. -/
def countdownStep : Nat -> Nat
  | 0 => 0
  | n + 1 => n

/-- One countdown step never increases the current value. -/
theorem countdownStep_le_self
    (n : Nat) :
    countdownStep n <= n := by
  cases n with
  | zero =>
      exact Nat.le_refl 0
  | succ n =>
      exact Nat.le_succ n

/-- Every value on a countdown trajectory is bounded by its start value. -/
theorem natTrajectory_countdown_le_start
    (n t : Nat) :
    natTrajectory countdownStep n t <= n := by
  induction t with
  | zero =>
      exact Nat.le_refl n
  | succ t ih =>
      exact Nat.le_trans
        (countdownStep_le_self (natTrajectory countdownStep n t))
        ih

/-- A shifted countdown trajectory started at `n + k` reaches `n` after `k` steps. -/
theorem natTrajectory_countdown_shift
    (n k : Nat) :
    natTrajectory countdownStep (n + k) k = n := by
  induction k generalizing n with
  | zero =>
      rw [Nat.add_zero]
      rfl
  | succ k ih =>
      change countdownStep (natTrajectory countdownStep (n + (k + 1)) k) = n
      have hStart : n + (k + 1) = (n + 1) + k := by
        rw [Nat.add_assoc, Nat.add_comm 1 k, <- Nat.add_assoc]
      rw [hStart, ih (n + 1)]
      rfl

/-- A countdown trajectory started at `n` reaches zero after `n` steps. -/
theorem natTrajectory_countdown_at_self
    (n : Nat) :
    natTrajectory countdownStep n n = 0 := by
  simpa using natTrajectory_countdown_shift 0 n

/-- Once countdown reaches zero, the next step is still zero. -/
theorem natTrajectory_countdown_after_self
    (n : Nat) :
    natTrajectory countdownStep n (n + 1) = 0 := by
  change countdownStep (natTrajectory countdownStep n n) = 0
  rw [natTrajectory_countdown_at_self n]
  rfl

/-- The countdown dynamics has an intrinsic finite-prefix height certificate. -/
def countdownPrefixHeightCertificate
    (n : Nat) :
    NatTrajectoryFinitePrefixHeightCertificate countdownStep n where
  horizon := n + 1
  height := n
  peakTime := 0
  peak_le_horizon := Nat.zero_le (n + 1)
  peak_realizes_height := rfl
  bounds_prefix := by
    intro time _hTime
    exact natTrajectory_countdown_le_start n time

/--
The countdown maximum height carries its positive diagonal witness internally.
-/
def countdownPrefixHeightWithPositiveDiagonalWitness
    (n : Nat) :
    NatTrajectoryFinitePrefixHeightWithPositiveDiagonalWitness
      countdownStep
      n :=
  natTrajectoryFinitePrefixHeightWithPositiveDiagonalWitness
    (countdownPrefixHeightCertificate n)

/-- The countdown certificate contains the whole `n + 2` bounded window. -/
def countdownPostPeakWindow
    (n : Nat) :
    NatTrajectoryPostPeakWindow
      (countdownPrefixHeightCertificate n) where
  post_window_within_prefix := by
    change 0 + (n + 1) <= n + 1
    rw [Nat.zero_add]
    exact Nat.le_refl (n + 1)

/-- Explicit terminal collision produced internally by countdown. -/
def countdownTerminalWindowCollision
    (n : Nat) :
    NatTrajectoryWindowCollision countdownStep n 0 (n + 2) where
  leftOffset := n
  rightOffset := n + 1
  left_lt_right := Nat.lt_succ_self n
  right_lt_length := Nat.lt_succ_self (n + 1)
  same_value := by
    rw [Nat.zero_add, Nat.zero_add]
    rw [natTrajectory_countdown_at_self n,
      natTrajectory_countdown_after_self n]

/--
Closed stability generated by the explicit terminal collision of the countdown
dynamics.
-/
def countdownTerminalCollisionClosedStabilityInstance
    (n : Nat) :
    RecoveredNonProjectiveClosedStabilityFromIntersection
      bidirectionalCompleteness
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (countdownTerminalWindowCollision n))))
      (List NatTraceAtom)
      NatInterfaceWitness
      NatInterfaceRealization
      (List Nat)
      tracePayloads
      NatInterfaceRepair :=
  windowCollisionClosedStabilityInstance
    (countdownTerminalWindowCollision n)

/--
Countdown closed-stability package carrying the realized maximum height, its
positive diagonal witness, and the explicit terminal collision together.
-/
structure CountdownClosedStabilityHeightPackage
    (n : Nat) where
  heightWithWitness :
    NatTrajectoryFinitePrefixHeightWithPositiveDiagonalWitness
      countdownStep
      n
  terminalCollision :
    NatTrajectoryWindowCollision countdownStep n 0 (n + 2)
  terminal_leftOffset_eq_height :
    terminalCollision.leftOffset = heightWithWitness.cert.height
  terminalClosedStability :
    RecoveredNonProjectiveClosedStabilityFromIntersection
      bidirectionalCompleteness
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            terminalCollision)))
      (List NatTraceAtom)
      NatInterfaceWitness
      NatInterfaceRealization
      (List Nat)
      tracePayloads
      NatInterfaceRepair

/--
Canonical countdown package: the final closed-stability instance is carried by
the maximum-height positive diagonal witness and by the explicit terminal
collision.
-/
def countdownClosedStabilityHeightPackage
    (n : Nat) :
    CountdownClosedStabilityHeightPackage n where
  heightWithWitness := countdownPrefixHeightWithPositiveDiagonalWitness n
  terminalCollision := countdownTerminalWindowCollision n
  terminal_leftOffset_eq_height := rfl
  terminalClosedStability :=
    countdownTerminalCollisionClosedStabilityInstance n

/--
Countdown post-peak package carrying the maximum-height positive diagonal
witness and the post-peak closure generated from that same certificate.
-/
def countdownPostPeakClosedStabilityHeightPackage
    (n : Nat) :
    NatTrajectoryPostPeakClosedStabilityHeightPackage
      (countdownPrefixHeightWithPositiveDiagonalWitness n) :=
  natTrajectoryPostPeakClosedStabilityHeightPackage
    (countdownPostPeakWindow n)

/--
Closed stability generated by the bounded-window/pigeonhole pipeline from the
intrinsic countdown finite-prefix certificate.
-/
def countdownPostPeakClosedStabilityInstance
    (n : Nat) :
    RecoveredNonProjectiveClosedStabilityFromIntersection
      bidirectionalCompleteness
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (windowCollision_of_boundedWindow
              (boundedWindow_of_postPeakWindow
                (countdownPostPeakWindow n))))))
      (List NatTraceAtom)
      NatInterfaceWitness
      NatInterfaceRealization
      (List Nat)
      tracePayloads
      NatInterfaceRepair :=
  (countdownPostPeakClosedStabilityHeightPackage n).closedStability

/--
Fully constructed enriched Nat closed-stability instance.

The final instance is driven by the intrinsic countdown dynamics and by its
explicit terminal collision.  The bounded-window/pigeonhole route remains
available above, but it is not the principal instance: the terminal endpoint is
formed directly.
-/
def fullyConstructedEnrichedNatClosedStabilityInstance
    (n : Nat) :
    RecoveredNonProjectiveClosedStabilityFromIntersection
      bidirectionalCompleteness
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (countdownTerminalWindowCollision n))))
      (List NatTraceAtom)
      NatInterfaceWitness
      NatInterfaceRealization
      (List Nat)
      tracePayloads
      NatInterfaceRepair :=
  (countdownClosedStabilityHeightPackage n).terminalClosedStability

end EnrichedNatClosedStabilityInstance
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownStep
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalWindowCollision
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownPrefixHeightWithPositiveDiagonalWitness
#print axioms Meta.EnrichedNatClosedStabilityInstance.CountdownClosedStabilityHeightPackage
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownClosedStabilityHeightPackage
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownPostPeakClosedStabilityHeightPackage
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownPostPeakClosedStabilityInstance
#print axioms Meta.EnrichedNatClosedStabilityInstance.fullyConstructedEnrichedNatClosedStabilityInstance
/- AXIOM_AUDIT_END -/
