import Meta.Arithmetic.GapContraction
import Meta.Arithmetic.CountdownDynamicGap
import Meta.Arithmetic.TwoPole
import Meta.Arithmetic.Parity

/-!
# Countdown arithmetic gap contraction

This file contains the countdown-specific arithmetic contraction row.  The
generic arithmetic contraction layer remains independent of the countdown
instance.
-/

namespace Meta
namespace EnrichedNatClosedStabilityInstance

open ClosedStabilityTheorem

/-- The primitive intersection generated by the terminal return of countdown. -/
def countdownTerminalIntersection
    (n : Nat) :
    PrimitiveMemoryReadingIntersection
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (countdownTerminalWindowCollision n)))) :=
  repeatedIndexIntersection
    (repeatedIndexCollision_of_trajectoryCollision
      (trajectoryCollision_of_windowCollision
        (countdownTerminalWindowCollision n)))

/-- The countdown terminal intersection carries the countdown terminal time. -/
theorem countdownTerminalIntersection_terminalTime_eq
    (n : Nat) :
    terminalTimeOfIntersection (countdownTerminalIntersection n) =
      countdownTerminalTime n := by
  unfold countdownTerminalIntersection
  unfold terminalTimeOfIntersection
  unfold countdownTerminalTime
  rfl

/-- The intrinsic countdown terminal excess is the successor of its terminal time. -/
theorem countdownArithmeticGapTerminalExcess_eq_terminalTime_succ
    (n : Nat) :
    formedPositiveExcessOfIntersection (countdownTerminalIntersection n) =
        countdownTerminalTime n + 1 := by
  unfold countdownTerminalIntersection
  exact countdownTerminalExcess_eq_terminalTime_succ n

/-- The intrinsic countdown dynamic arithmetic gap has terminal excess `n + 2`. -/
theorem countdownArithmeticGapTerminalExcess_eq_n_plus_two
    (n : Nat) :
    formedPositiveExcessOfIntersection (countdownTerminalIntersection n) =
        n + 2 :=
  countdownTerminalExcess_eq_n_plus_two n

/-! ## Countdown parity codes -/

/-- The terminal countdown dynamic row stores the same `n + 2` excess. -/
theorem countdownTerminalDynamicGapRow_terminalExcess_eq_n_plus_two
    (n : Nat) :
    (countdownTerminalDynamicGapRow n).terminalExcess = n + 2 := by
  unfold countdownTerminalDynamicGapRow
  unfold windowCollisionDynamicGapRow
  unfold trajectoryDynamicGapRow
  unfold repeatedIndexDynamicGapRow
  unfold arithmeticDynamicGapRowOfIntersection
  exact countdownTerminalExcess_eq_n_plus_two n

/-- The terminal countdown dynamic row stores terminal time `n + 1`. -/
theorem countdownTerminalDynamicGapRow_terminalTime_eq_n_plus_one
    (n : Nat) :
    (countdownTerminalDynamicGapRow n).terminalTime = n + 1 := by
  unfold countdownTerminalDynamicGapRow
  unfold windowCollisionDynamicGapRow
  unfold trajectoryDynamicGapRow
  unfold repeatedIndexDynamicGapRow
  unfold arithmeticDynamicGapRowOfIntersection
  exact countdownTerminalTime_eq_n_plus_one n

/-- The terminal countdown dynamic row stores excess one step after terminal time. -/
theorem countdownTerminalDynamicGapRow_terminalExcess_eq_terminalTime_succ
    (n : Nat) :
    (countdownTerminalDynamicGapRow n).terminalExcess =
      (countdownTerminalDynamicGapRow n).terminalTime + 1 :=
  arithmeticDynamicGapRow_terminalExcess_eq_terminalTime_succ
    (countdownTerminalDynamicGapRow n)

/-- The fully constructed countdown dynamic row stores the same `n + 2` excess. -/
theorem fullyConstructedCountdownDynamicGapRow_terminalExcess_eq_n_plus_two
    (n : Nat) :
    (fullyConstructedCountdownDynamicGapRow n).terminalExcess = n + 2 := by
  unfold fullyConstructedCountdownDynamicGapRow
  exact countdownTerminalDynamicGapRow_terminalExcess_eq_n_plus_two n

/-- The fully constructed countdown dynamic row stores terminal time `n + 1`. -/
theorem fullyConstructedCountdownDynamicGapRow_terminalTime_eq_n_plus_one
    (n : Nat) :
    (fullyConstructedCountdownDynamicGapRow n).terminalTime = n + 1 := by
  unfold fullyConstructedCountdownDynamicGapRow
  exact countdownTerminalDynamicGapRow_terminalTime_eq_n_plus_one n

/-- The fully constructed countdown dynamic row stores excess after terminal time. -/
theorem fullyConstructedCountdownDynamicGapRow_terminalExcess_eq_terminalTime_succ
    (n : Nat) :
    (fullyConstructedCountdownDynamicGapRow n).terminalExcess =
      (fullyConstructedCountdownDynamicGapRow n).terminalTime + 1 :=
  arithmeticDynamicGapRow_terminalExcess_eq_terminalTime_succ
    (fullyConstructedCountdownDynamicGapRow n)

/-- The countdown closing role is the closing excess role at `n + 2`. -/
theorem countdownTerminalClosingRole_eq_n_plus_two
    (n : Nat) :
    arithmeticClosingRoleOfIntersection (countdownTerminalIntersection n) =
      NatEnrichedParityRole.closingExcess (n + 2) := by
  rw [arithmeticClosingRoleOfIntersection_eq,
    countdownArithmeticGapTerminalExcess_eq_n_plus_two]

/-- The countdown closing role is indexed by the successor of the terminal time. -/
theorem countdownTerminalClosingRole_eq_terminalTime_succ
    (n : Nat) :
    arithmeticClosingRoleOfIntersection (countdownTerminalIntersection n) =
      NatEnrichedParityRole.closingExcess (countdownTerminalTime n + 1) := by
  rw [arithmeticClosingRoleOfIntersection_eq,
    countdownArithmeticGapTerminalExcess_eq_terminalTime_succ]

/-- The countdown mediating role is the mediating value role at `n + 2`. -/
theorem countdownTerminalMediatingRole_eq_n_plus_two
    (n : Nat) :
    arithmeticMediatingRoleOfIntersection (countdownTerminalIntersection n) =
      NatEnrichedParityRole.mediatingValue (n + 2) := by
  rw [arithmeticMediatingRoleOfIntersection_eq,
    countdownArithmeticGapTerminalExcess_eq_n_plus_two]

/-- The countdown mediating role is indexed by the successor of the terminal time. -/
theorem countdownTerminalMediatingRole_eq_terminalTime_succ
    (n : Nat) :
    arithmeticMediatingRoleOfIntersection (countdownTerminalIntersection n) =
      NatEnrichedParityRole.mediatingValue (countdownTerminalTime n + 1) := by
  rw [arithmeticMediatingRoleOfIntersection_eq,
    countdownArithmeticGapTerminalExcess_eq_terminalTime_succ]

/-- Arithmetic closing code extracted from the countdown terminal return. -/
def countdownTerminalClosingCode
    (n : Nat) :
    Nat :=
  arithmeticClosingCodeOfIntersection
    (countdownTerminalIntersection n)

/-- Arithmetic mediating code extracted from the countdown terminal return. -/
def countdownTerminalMediatingCode
    (n : Nat) :
    Nat :=
  arithmeticMediatingCodeOfIntersection
    (countdownTerminalIntersection n)

/-- The countdown closing code is exactly `2 * (n + 2)`. -/
theorem countdownTerminalClosingCode_eq_n_plus_two
    (n : Nat) :
    countdownTerminalClosingCode n = 2 * (n + 2) := by
  unfold countdownTerminalClosingCode
  rw [arithmeticClosingCodeOfIntersection_eq,
    countdownArithmeticGapTerminalExcess_eq_n_plus_two]

/-- The countdown mediating code is exactly `2 * (n + 2) + 1`. -/
theorem countdownTerminalMediatingCode_eq_n_plus_two
    (n : Nat) :
    countdownTerminalMediatingCode n = 2 * (n + 2) + 1 := by
  unfold countdownTerminalMediatingCode
  rw [arithmeticMediatingCodeOfIntersection_eq,
    countdownArithmeticGapTerminalExcess_eq_n_plus_two]

/-- The countdown closing code is even in Mathlib's constructive `Even` sense. -/
theorem countdownTerminalClosingCode_even
    (n : Nat) :
    Even (countdownTerminalClosingCode n) :=
  arithmeticClosingCodeOfIntersection_even
    (countdownTerminalIntersection n)

/-- The countdown mediating code is odd in the constructive `2*k+1` sense. -/
theorem countdownTerminalMediatingCode_oddClassical
    (n : Nat) :
    OddClassical (countdownTerminalMediatingCode n) :=
  arithmeticMediatingCodeOfIntersection_oddClassical
    (countdownTerminalIntersection n)

/-! ## Countdown two-pole realization -/

/-- The countdown terminal collision realizes an arithmetic operational two-pole interface. -/
def countdownTerminalOperationalTwoPole
    (n : Nat) :
    OperationalTwoPole
      ArithmeticEnrichedInterface
      ArithmeticVisiblePayload
      arithmeticPayloadProjection
      NatInterfaceRepair :=
  arithmeticDynamicRowOperationalTwoPole
    (countdownTerminalDynamicGapRow n)

/-- The countdown terminal collision realizes an arithmetic structural two-pole interface. -/
def countdownTerminalStructuralTwoPole
    (n : Nat) :
    StructuralTwoPole
      ArithmeticEnrichedInterface
      ArithmeticVisiblePayload
      arithmeticPayloadProjection :=
  operationalTwoPole_structural
    (countdownTerminalOperationalTwoPole n)

/-- The fully constructed countdown row realizes the same operational two-pole interface. -/
def fullyConstructedCountdownOperationalTwoPole
    (n : Nat) :
    OperationalTwoPole
      ArithmeticEnrichedInterface
      ArithmeticVisiblePayload
      arithmeticPayloadProjection
      NatInterfaceRepair :=
  arithmeticDynamicRowOperationalTwoPole
    (fullyConstructedCountdownDynamicGapRow n)

/-- The fully constructed countdown row realizes a structural two-pole interface. -/
def fullyConstructedCountdownStructuralTwoPole
    (n : Nat) :
    StructuralTwoPole
      ArithmeticEnrichedInterface
      ArithmeticVisiblePayload
      arithmeticPayloadProjection :=
  operationalTwoPole_structural
    (fullyConstructedCountdownOperationalTwoPole n)

end EnrichedNatClosedStabilityInstance
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalIntersection
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalIntersection_terminalTime_eq
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticGapTerminalExcess_eq_terminalTime_succ
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticGapTerminalExcess_eq_n_plus_two
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalDynamicGapRow_terminalExcess_eq_n_plus_two
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalDynamicGapRow_terminalTime_eq_n_plus_one
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalDynamicGapRow_terminalExcess_eq_terminalTime_succ
#print axioms Meta.EnrichedNatClosedStabilityInstance.fullyConstructedCountdownDynamicGapRow_terminalExcess_eq_n_plus_two
#print axioms Meta.EnrichedNatClosedStabilityInstance.fullyConstructedCountdownDynamicGapRow_terminalTime_eq_n_plus_one
#print axioms Meta.EnrichedNatClosedStabilityInstance.fullyConstructedCountdownDynamicGapRow_terminalExcess_eq_terminalTime_succ
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalClosingRole_eq_n_plus_two
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalMediatingRole_eq_n_plus_two
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalClosingRole_eq_terminalTime_succ
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalMediatingRole_eq_terminalTime_succ
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalClosingCode
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalMediatingCode
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalClosingCode_eq_n_plus_two
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalMediatingCode_eq_n_plus_two
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalClosingCode_even
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalMediatingCode_oddClassical
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalOperationalTwoPole
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownTerminalStructuralTwoPole
#print axioms Meta.EnrichedNatClosedStabilityInstance.fullyConstructedCountdownOperationalTwoPole
#print axioms Meta.EnrichedNatClosedStabilityInstance.fullyConstructedCountdownStructuralTwoPole
/- AXIOM_AUDIT_END -/
