import Meta.Arithmetic.HeightDiagonal

/-!
# Arithmetic dynamic gap facade

This file exposes the generic dynamic Nat gap layer.

It exposes the common dynamic row:

* formed trace;
* payload-only shadow;
* shared visible payload;
* positive terminal excess;
* projective obstruction;
* local recovery.

Countdown-specific terminal rows are kept in `CountdownDynamicGap.lean`.
-/

namespace Meta
namespace EnrichedNatClosedStabilityInstance

open ClosedStabilityTheorem

/-! ## Dynamic gap row -/

/-- Terminal time carried by one primitive arithmetic intersection. -/
def terminalTimeOfIntersection
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    Nat :=
  intersection.excess

/-- The formed positive excess is the successor of the terminal time. -/
theorem formedPositiveExcessOfIntersection_eq_terminalTime_succ
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    formedPositiveExcessOfIntersection intersection =
      terminalTimeOfIntersection intersection + 1 :=
  rfl

/--
Public row of an arithmetic dynamic gap.

The row records both sides of the projection collision: the enriched formed
trace and the payload-only shadow.  They have the same visible payload but are
separated as enriched traces.  The row also carries the obstruction and local
recovery generated by the same intersection.
-/
structure ArithmeticDynamicGapRow where
  formed : List NatTraceAtom
  shadow : List NatTraceAtom
  visible : List Nat
  terminalTime : Nat
  terminalExcess : Nat
  terminalExcess_eq_terminalTime_succ :
    terminalExcess = terminalTime + 1
  sameVisible : tracePayloads formed = tracePayloads shadow
  separated : formed = shadow -> False
  obstruction :
    ProjectionObstruction
      (List NatTraceAtom)
      (List Nat)
      tracePayloads
  recovery :
    LocalProjectiveRecovery
      (List NatTraceAtom)
      (List Nat)
      tracePayloads
      NatInterfaceRepair
  recovery_formed : recovery.formed = formed
  recovery_shadow : recovery.shadow = shadow

/--
Final row coupling an arithmetic dynamic gap with the recovered closed-stability
instance generated by the same dynamic source.
-/
structure ArithmeticDynamicClosedStabilityRow
    (branch : MemoryBranch) where
  gapRow : ArithmeticDynamicGapRow
  closedStability :
    RecoveredNonProjectiveClosedStabilityFromIntersection
      bidirectionalCompleteness
      branch
      (List NatTraceAtom)
      NatInterfaceWitness
      NatInterfaceRealization
      (List Nat)
      tracePayloads
      NatInterfaceRepair

/-- The dynamic gap row generated by an exact primitive intersection. -/
def arithmeticDynamicGapRowOfIntersection
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    ArithmeticDynamicGapRow where
  formed := formedTraceOfIntersection intersection
  shadow := payloadOnlyTraceOfIntersection intersection
  visible := tracePayloads (payloadOnlyTraceOfIntersection intersection)
  terminalTime := terminalTimeOfIntersection intersection
  terminalExcess := formedPositiveExcessOfIntersection intersection
  terminalExcess_eq_terminalTime_succ :=
    formedPositiveExcessOfIntersection_eq_terminalTime_succ intersection
  sameVisible := formedTraceOfIntersection_same_payloadOnlyPayload intersection
  separated := formedTraceOfIntersection_ne_payloadOnlyTrace intersection
  obstruction := payloadProjectionObstructionOfIntersection intersection
  recovery := localProjectiveRecoveryOfIntersection intersection
  recovery_formed := rfl
  recovery_shadow := rfl

/-- Every arithmetic dynamic gap row stores an excess one step after its terminal time. -/
theorem arithmeticDynamicGapRow_terminalExcess_eq_terminalTime_succ
    (row : ArithmeticDynamicGapRow) :
    row.terminalExcess = row.terminalTime + 1 :=
  row.terminalExcess_eq_terminalTime_succ

/-! ## Repeated-index lock -/

/-- The primitive repeated-index intersection stores `secondTime` as excess. -/
theorem repeatedIndexIntersection_excess_eq
    (collision : RepeatedIndexCollision) :
    (repeatedIndexIntersection collision).excess = collision.secondTime :=
  rfl

/-- The repeated-index terminal time is the second collision time. -/
theorem repeatedIndexTerminalTime_eq_secondTime
    (collision : RepeatedIndexCollision) :
    terminalTimeOfIntersection (repeatedIndexIntersection collision) =
      collision.secondTime :=
  rfl

/-- The terminal excess of a repeated-index dynamic gap is `secondTime + 1`. -/
theorem repeatedIndexTerminalExcess_eq
    (collision : RepeatedIndexCollision) :
    formedPositiveExcessOfIntersection
      (repeatedIndexIntersection collision) =
        collision.secondTime + 1 :=
  rfl

/-- The repeated-index formed trace and payload-only shadow share payload. -/
theorem repeatedIndexDynamicGap_sameVisible
    (collision : RepeatedIndexCollision) :
    tracePayloads
      (formedTraceOfIntersection (repeatedIndexIntersection collision)) =
        tracePayloads
          (payloadOnlyTraceOfIntersection
            (repeatedIndexIntersection collision)) :=
  formedTraceOfIntersection_same_payloadOnlyPayload
    (repeatedIndexIntersection collision)

/-- The repeated-index formed trace is not the payload-only shadow. -/
theorem repeatedIndexDynamicGap_separated
    (collision : RepeatedIndexCollision) :
    formedTraceOfIntersection (repeatedIndexIntersection collision) =
      payloadOnlyTraceOfIntersection (repeatedIndexIntersection collision) ->
        False :=
  formedTraceOfIntersection_ne_payloadOnlyTrace
    (repeatedIndexIntersection collision)

/-- Public dynamic gap row generated by a repeated-index collision. -/
def repeatedIndexDynamicGapRow
    (collision : RepeatedIndexCollision) :
    ArithmeticDynamicGapRow :=
  arithmeticDynamicGapRowOfIntersection
    (repeatedIndexIntersection collision)

/-- The repeated-index dynamic row stores `secondTime` as terminal time. -/
theorem repeatedIndexDynamicGapRow_terminalTime_eq_secondTime
    (collision : RepeatedIndexCollision) :
    (repeatedIndexDynamicGapRow collision).terminalTime =
      collision.secondTime :=
  rfl

/-- Final repeated-index row: dynamic gap plus recovered closed stability. -/
def repeatedIndexDynamicClosedStabilityRow
    (collision : RepeatedIndexCollision) :
    ArithmeticDynamicClosedStabilityRow
      (repeatedIndexBranch collision) where
  gapRow := repeatedIndexDynamicGapRow collision
  closedStability := repeatedIndexClosedStabilityInstance collision

/-! ## Trajectory lock -/

/--
A repeated value in a Nat trajectory has terminal excess `secondTime + 1`.
-/
theorem trajectoryCollision_terminalTime_eq
    {step : Nat -> Nat}
    {start : Nat}
    (collision : NatTrajectoryRepeatedIndexCollision step start) :
    terminalTimeOfIntersection
      (repeatedIndexIntersection
        (repeatedIndexCollision_of_trajectoryCollision collision)) =
        collision.secondTime :=
  rfl

/--
A repeated value in a Nat trajectory has terminal excess `secondTime + 1`.
-/
theorem trajectoryCollision_terminalExcess_eq
    {step : Nat -> Nat}
    {start : Nat}
    (collision : NatTrajectoryRepeatedIndexCollision step start) :
    formedPositiveExcessOfIntersection
      (repeatedIndexIntersection
        (repeatedIndexCollision_of_trajectoryCollision collision)) =
        collision.secondTime + 1 :=
  rfl

/-- Public dynamic gap row generated by a repeated value in one trajectory. -/
def trajectoryDynamicGapRow
    {step : Nat -> Nat}
    {start : Nat}
    (collision : NatTrajectoryRepeatedIndexCollision step start) :
    ArithmeticDynamicGapRow :=
  repeatedIndexDynamicGapRow
    (repeatedIndexCollision_of_trajectoryCollision collision)

/-- The trajectory dynamic row stores the collision's second time as terminal time. -/
theorem trajectoryDynamicGapRow_terminalTime_eq
    {step : Nat -> Nat}
    {start : Nat}
    (collision : NatTrajectoryRepeatedIndexCollision step start) :
    (trajectoryDynamicGapRow collision).terminalTime =
      collision.secondTime :=
  rfl

/-- Final trajectory row: dynamic gap plus recovered closed stability. -/
def trajectoryDynamicClosedStabilityRow
    {step : Nat -> Nat}
    {start : Nat}
    (collision : NatTrajectoryRepeatedIndexCollision step start) :
    ArithmeticDynamicClosedStabilityRow
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision collision)) where
  gapRow := trajectoryDynamicGapRow collision
  closedStability := trajectoryRepeatedIndexClosedStabilityInstance collision

/-! ## Window lock -/

/--
A finite-window collision has terminal excess at the absolute right time.
-/
theorem windowCollision_terminalTime_eq
    {step : Nat -> Nat}
    {start windowStart windowLength : Nat}
    (collision :
      NatTrajectoryWindowCollision step start windowStart windowLength) :
    terminalTimeOfIntersection
      (repeatedIndexIntersection
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision collision))) =
        windowStart + collision.rightOffset :=
  rfl

/--
A finite-window collision has terminal excess at the absolute right time.
-/
theorem windowCollision_terminalExcess_eq
    {step : Nat -> Nat}
    {start windowStart windowLength : Nat}
    (collision :
      NatTrajectoryWindowCollision step start windowStart windowLength) :
    formedPositiveExcessOfIntersection
      (repeatedIndexIntersection
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision collision))) =
        windowStart + collision.rightOffset + 1 :=
  rfl

/-- Public dynamic gap row generated by a finite-window collision. -/
def windowCollisionDynamicGapRow
    {step : Nat -> Nat}
    {start windowStart windowLength : Nat}
    (collision :
      NatTrajectoryWindowCollision step start windowStart windowLength) :
    ArithmeticDynamicGapRow :=
  trajectoryDynamicGapRow
    (trajectoryCollision_of_windowCollision collision)

/-- The window dynamic row stores the absolute right time as terminal time. -/
theorem windowCollisionDynamicGapRow_terminalTime_eq
    {step : Nat -> Nat}
    {start windowStart windowLength : Nat}
    (collision :
      NatTrajectoryWindowCollision step start windowStart windowLength) :
    (windowCollisionDynamicGapRow collision).terminalTime =
      windowStart + collision.rightOffset :=
  rfl

/-- Final window-collision row: dynamic gap plus recovered closed stability. -/
def windowCollisionDynamicClosedStabilityRow
    {step : Nat -> Nat}
    {start windowStart windowLength : Nat}
    (collision :
      NatTrajectoryWindowCollision step start windowStart windowLength) :
    ArithmeticDynamicClosedStabilityRow
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision collision))) where
  gapRow := windowCollisionDynamicGapRow collision
  closedStability := windowCollisionClosedStabilityInstance collision

/-- Public dynamic gap row constructively produced by a bounded window. -/
def boundedWindowDynamicGapRow
    {step : Nat -> Nat}
    {start windowStart B : Nat}
    (window : NatTrajectoryBoundedWindow step start windowStart B) :
    ArithmeticDynamicGapRow :=
  windowCollisionDynamicGapRow
    (windowCollision_of_boundedWindow window)

/-- Final bounded-window row: produced gap plus recovered closed stability. -/
def boundedWindowDynamicClosedStabilityRow
    {step : Nat -> Nat}
    {start windowStart B : Nat}
    (window : NatTrajectoryBoundedWindow step start windowStart B) :
    ArithmeticDynamicClosedStabilityRow
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (windowCollision_of_boundedWindow window)))) where
  gapRow := boundedWindowDynamicGapRow window
  closedStability := boundedWindowClosedStabilityInstance window

/-! ## Height and post-peak lock -/

/-- The canonical positive diagonal at height has terminal excess `1`. -/
theorem canonicalPositiveDiagonalTerminalExcess_eq_one
    (height : Nat) :
    formedPositiveExcessOfIntersection
      (canonicalIntersection height) = 1 :=
  rfl

/-- Public dynamic gap row generated from a post-peak finite-prefix window. -/
def postPeakWindowDynamicGapRow
    {step : Nat -> Nat}
    {start : Nat}
    {cert : NatTrajectoryFinitePrefixHeightCertificate step start}
    (window : NatTrajectoryPostPeakWindow cert) :
    ArithmeticDynamicGapRow :=
  boundedWindowDynamicGapRow
    (boundedWindow_of_postPeakWindow window)

/-- Final post-peak row: produced gap plus recovered closed stability. -/
def postPeakWindowDynamicClosedStabilityRow
    {step : Nat -> Nat}
    {start : Nat}
    {cert : NatTrajectoryFinitePrefixHeightCertificate step start}
    (window : NatTrajectoryPostPeakWindow cert) :
    ArithmeticDynamicClosedStabilityRow
      (repeatedIndexBranch
        (repeatedIndexCollision_of_trajectoryCollision
          (trajectoryCollision_of_windowCollision
            (windowCollision_of_boundedWindow
              (boundedWindow_of_postPeakWindow window))))) where
  gapRow := postPeakWindowDynamicGapRow window
  closedStability := postPeakWindowClosedStabilityInstance window

end EnrichedNatClosedStabilityInstance
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.EnrichedNatClosedStabilityInstance.terminalTimeOfIntersection
#print axioms Meta.EnrichedNatClosedStabilityInstance.formedPositiveExcessOfIntersection_eq_terminalTime_succ
#print axioms Meta.EnrichedNatClosedStabilityInstance.ArithmeticDynamicGapRow
#print axioms Meta.EnrichedNatClosedStabilityInstance.ArithmeticDynamicClosedStabilityRow
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticDynamicGapRowOfIntersection
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticDynamicGapRow_terminalExcess_eq_terminalTime_succ
#print axioms Meta.EnrichedNatClosedStabilityInstance.repeatedIndexTerminalTime_eq_secondTime
#print axioms Meta.EnrichedNatClosedStabilityInstance.repeatedIndexTerminalExcess_eq
#print axioms Meta.EnrichedNatClosedStabilityInstance.repeatedIndexDynamicGapRow
#print axioms Meta.EnrichedNatClosedStabilityInstance.repeatedIndexDynamicGapRow_terminalTime_eq_secondTime
#print axioms Meta.EnrichedNatClosedStabilityInstance.repeatedIndexDynamicClosedStabilityRow
#print axioms Meta.EnrichedNatClosedStabilityInstance.trajectoryCollision_terminalTime_eq
#print axioms Meta.EnrichedNatClosedStabilityInstance.trajectoryCollision_terminalExcess_eq
#print axioms Meta.EnrichedNatClosedStabilityInstance.trajectoryDynamicGapRow
#print axioms Meta.EnrichedNatClosedStabilityInstance.trajectoryDynamicGapRow_terminalTime_eq
#print axioms Meta.EnrichedNatClosedStabilityInstance.trajectoryDynamicClosedStabilityRow
#print axioms Meta.EnrichedNatClosedStabilityInstance.windowCollision_terminalTime_eq
#print axioms Meta.EnrichedNatClosedStabilityInstance.windowCollision_terminalExcess_eq
#print axioms Meta.EnrichedNatClosedStabilityInstance.windowCollisionDynamicGapRow_terminalTime_eq
#print axioms Meta.EnrichedNatClosedStabilityInstance.boundedWindowDynamicGapRow
#print axioms Meta.EnrichedNatClosedStabilityInstance.windowCollisionDynamicClosedStabilityRow
#print axioms Meta.EnrichedNatClosedStabilityInstance.boundedWindowDynamicClosedStabilityRow
#print axioms Meta.EnrichedNatClosedStabilityInstance.canonicalPositiveDiagonalTerminalExcess_eq_one
#print axioms Meta.EnrichedNatClosedStabilityInstance.postPeakWindowDynamicGapRow
#print axioms Meta.EnrichedNatClosedStabilityInstance.postPeakWindowDynamicClosedStabilityRow
/- AXIOM_AUDIT_END -/
