import Meta.Arithmetic.ParityNames
import Meta.Arithmetic.ArithmeticIntersectionPole

/-!
# Arithmetic dynamic parity instances

This file connects an oriented arithmetic intersection pole to the abstract
dynamic parity separation and packages the resulting arithmetic parity roles.
-/

namespace Meta
namespace EnrichedNatClosedStabilityInstance

open ClosedStabilityTheorem

/-! ## Dynamic parity instance generated by an intersection -/

/-- The dynamic parity raccord generated by one arithmetic intersection. -/
def arithmeticIntersectionParityRaccord
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    DynamicParitySeparation
      (arithmeticIntersectionDynamicReturn intersection) :=
  dynamicParitySeparation_leftRight
    (arithmeticIntersectionDynamicReturn intersection)
    (fun
      | ArithmeticIntersectionPole.formed => ParityRegime.left
      | ArithmeticIntersectionPole.shadow => ParityRegime.right)
    (fun _ => ParityVisible.contracted)
    rfl
    rfl
    rfl
    rfl

/-- Operational parity roles produced by one arithmetic intersection. -/
def arithmeticIntersectionOperationalParityRoles
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    OperationalParityRoles
      (arithmeticIntersectionParityRaccord intersection) :=
  operationalParityRolesOfDynamicParitySeparation
    (arithmeticIntersectionParityRaccord intersection)

/-- Arithmetic parity roles produced by one arithmetic intersection. -/
def arithmeticIntersectionArithmeticParityRoles
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    ArithmeticParityRoles
      (arithmeticIntersectionOperationalParityRoles intersection) :=
  arithmeticParityRolesOfOperationalRoles
    (arithmeticIntersectionOperationalParityRoles intersection)

/-! ## Packaged arithmetic dynamic parity instance -/

/-- Full arithmetic dynamic parity instance generated by one intersection. -/
structure ArithmeticDynamicParityInstance
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) where
  dynamicReturn :
    LocallyRecoveredDynamicReturn
      bidirectionalCompleteness
      enrichedNatRoundTripCoherence
      branch
      PUnit
      (ArithmeticIntersectionPole intersection)
      arithmeticIntersectionPoleWitness
      arithmeticIntersectionPoleRealization
      (List Nat)
      arithmeticIntersectionPoleVisible
      arithmeticIntersectionPoleRepair
  parityRaccord : DynamicParitySeparation dynamicReturn
  operationalRoles : OperationalParityRoles parityRaccord
  arithmeticRoles : ArithmeticParityRoles operationalRoles

/-- Canonical arithmetic dynamic parity instance generated by one intersection. -/
def arithmeticDynamicParityInstance
    {branch : MemoryBranch}
    (intersection : PrimitiveMemoryReadingIntersection branch) :
    ArithmeticDynamicParityInstance intersection where
  dynamicReturn := arithmeticIntersectionDynamicReturn intersection
  parityRaccord := arithmeticIntersectionParityRaccord intersection
  operationalRoles := arithmeticIntersectionOperationalParityRoles intersection
  arithmeticRoles := arithmeticIntersectionArithmeticParityRoles intersection

/-- The even and odd roles of an arithmetic dynamic parity instance have the same visible. -/
theorem arithmeticDynamicParityInstance_sameParityProjection
    {branch : MemoryBranch}
    {intersection : PrimitiveMemoryReadingIntersection branch}
    (parityInstance : ArithmeticDynamicParityInstance intersection) :
    parityProjection
        (arithmeticParityRoles_evenRegime parityInstance.arithmeticRoles) =
      parityProjection
        (arithmeticParityRoles_oddRegime parityInstance.arithmeticRoles) :=
  arithmeticParityRoles_sameParityProjection parityInstance.arithmeticRoles

/-- The even and odd roles of an arithmetic dynamic parity instance remain separated. -/
theorem arithmeticDynamicParityInstance_separated
    {branch : MemoryBranch}
    {intersection : PrimitiveMemoryReadingIntersection branch}
    (parityInstance : ArithmeticDynamicParityInstance intersection) :
    arithmeticParityRoles_evenRegime parityInstance.arithmeticRoles =
      arithmeticParityRoles_oddRegime parityInstance.arithmeticRoles -> False :=
  arithmeticParityRoles_separated parityInstance.arithmeticRoles

/--
An arithmetic dynamic parity instance rules out global reconstruction from the
contracted parity visible alone.
-/
def arithmeticDynamicParityInstance_noParityVisibleReconstruction
    {branch : MemoryBranch}
    {intersection : PrimitiveMemoryReadingIntersection branch}
    (parityInstance : ArithmeticDynamicParityInstance intersection) :
    ((recover : ParityVisible -> ParityRegime) ->
      ((regime : ParityRegime) ->
        recover (parityProjection regime) = regime) ->
      False) :=
  operationalParityRoles_noParityVisibleReconstruction
    parityInstance.operationalRoles

end EnrichedNatClosedStabilityInstance
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionParityRaccord
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionOperationalParityRoles
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionArithmeticParityRoles
#print axioms Meta.EnrichedNatClosedStabilityInstance.ArithmeticDynamicParityInstance
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticDynamicParityInstance
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticDynamicParityInstance_sameParityProjection
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticDynamicParityInstance_separated
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticDynamicParityInstance_noParityVisibleReconstruction
/- AXIOM_AUDIT_END -/
