import Meta.Arithmetic.CountdownParity

/-!
# Arithmetic parity roles

This compatibility module keeps `Meta.Arithmetic.ParityRoles` as the public
entry point while the implementation is split across:

* `ParityNames.lean`;
* `ArithmeticIntersectionPole.lean`;
* `DynamicParityInstance.lean`;
* `CountdownParity.lean`.

Downstream files can continue importing `Meta.Arithmetic.ParityRoles`.
-/

namespace Meta
namespace EnrichedNatClosedStabilityInstance

/-! ## Public compatibility audit -/

end EnrichedNatClosedStabilityInstance
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.EnrichedNatClosedStabilityInstance.ArithmeticParityRoles
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticParityRolesOfOperationalRoles
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticParityRoles_evenRegime
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticParityRoles_oddRegime
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticParityRoles_even_eq_closing
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticParityRoles_odd_eq_mediating
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticParityRoles_sameParityProjection
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticParityRoles_separated
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticParityRoles_dynamicRepair
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticParityRoles_noParityVisibleReconstruction
#print axioms Meta.EnrichedNatClosedStabilityInstance.ArithmeticIntersectionPole
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleTrace
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleVisible
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleRepair
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleTrace_formed
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleTrace_shadow
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleVisible_same
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleTrace_separated
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPole_separated
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionLocalRecovery
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleWitness
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionPoleRealization
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionDynamicReturn
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionParityRaccord
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionOperationalParityRoles
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticIntersectionArithmeticParityRoles
#print axioms Meta.EnrichedNatClosedStabilityInstance.ArithmeticDynamicParityInstance
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticDynamicParityInstance
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticDynamicParityInstance_sameParityProjection
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticDynamicParityInstance_separated
#print axioms Meta.EnrichedNatClosedStabilityInstance.arithmeticDynamicParityInstance_noParityVisibleReconstruction
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParityIntersection
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParityDynamicReturn
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParityRaccord
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownOperationalParityRoles
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParityRoles
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParityInstance
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParity_terminalExcess_eq_n_plus_two
#print axioms Meta.EnrichedNatClosedStabilityInstance.CountdownArithmeticParityPackage
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParityPackage
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParity_sameParityProjection
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParity_separated
#print axioms Meta.EnrichedNatClosedStabilityInstance.countdownArithmeticParity_noParityVisibleReconstruction
/- AXIOM_AUDIT_END -/
