import Meta.Core.CausalTotality
import Meta.Tarski.CausalAccumulatingSystem

/-!
# Historical totality of patchable Tarski repair

The generic cumulative-totality theorem is instantiated with intrinsic Tarski
causal memory.  In this concrete memory, every advance remembers exactly the
previous obligations together with the current diagonal gap.  The historical
totality contains an injective realization of all causal words, while no
realized stage exhausts it.

No comparison with `Nat` is imported or used.
-/

namespace Meta
namespace ClosedStabilityTheorem
namespace PatchableArithmeticTarskiContext

universe u v

/-! ## Exact Tarski memory extension -/

/-- A canonical Tarski advance adds exactly the current diagonal gap to the
previous extensional memory. -/
theorem tarskiAdvance_memory_iff
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (state : CausalState patchable initial)
    (sentence : patchable.context.Sentence) :
    (tarskiAccumulatingCausalSystem patchable initial).Memory
        ((tarskiAccumulatingCausalSystem patchable initial).advance state)
        sentence ↔
      (tarskiAccumulatingCausalSystem patchable initial).Memory
          state sentence ∨
        sentence =
          (tarskiAccumulatingCausalSystem patchable initial).gap state := by
  change
    (sentence = patchable.diagonalSentence state.current ∨
        CausalMemory.Remembers
          patchable initial state.memory sentence) ↔
      (CausalMemory.Remembers
          patchable initial state.memory sentence ∨
        sentence = patchable.diagonalSentence state.current)
  constructor
  · intro remembered
    cases remembered with
    | inl current =>
        exact Or.inr current
    | inr previous =>
        exact Or.inl previous
  · intro remembered
    cases remembered with
    | inl previous =>
        exact Or.inr previous
    | inr current =>
        exact Or.inl current

/-! ## Historical memory before `Nat` -/

/-- Historical Tarski memory is eventual remembrance along a finite causal
word from the intrinsic initial state. -/
def tarskiHistoricalMemory
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    patchable.context.Sentence -> Prop :=
  (tarskiAccumulatingCausalSystem patchable initial).HistoricalMemory
    (initialCausalState patchable initial)

/-- The diagonal gap generated by a Tarski causal word. -/
def tarskiHistoricalGap
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (word : CausalAdditive.CausalWord) :
    patchable.context.Sentence :=
  (tarskiAccumulatingCausalSystem patchable initial).historicalGap
    (initialCausalState patchable initial)
    word

/-- The subtype of sentences positively contained in historical Tarski
memory. -/
def TarskiHistoricalGap
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    Type u :=
  Subtype (tarskiHistoricalMemory patchable initial)

/-- Every causal word realizes a positive inhabitant of historical Tarski
memory. -/
def tarskiRealizedHistoricalGap
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (word : CausalAdditive.CausalWord) :
    TarskiHistoricalGap patchable initial :=
  (tarskiAccumulatingCausalSystem patchable initial).realizedHistoricalGap
    (initialCausalState patchable initial)
    word

/-- Every Tarski advance is a strict extension of extensional memory. -/
def tarskiAdvance_strictMemoryExtension
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (state : CausalState patchable initial) :
    CausalAdditive.StrictPredicateInclusion
      ((tarskiAccumulatingCausalSystem patchable initial).Memory state)
      ((tarskiAccumulatingCausalSystem patchable initial).Memory
        ((tarskiAccumulatingCausalSystem patchable initial).advance state)) :=
  (tarskiAccumulatingCausalSystem patchable initial)
    |>.advance_strictMemoryExtension state

/-- Every realized Tarski stage is strictly included in historical memory. -/
def tarskiStageMemory_strictlyIncluded_historical
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (word : CausalAdditive.CausalWord) :
    CausalAdditive.StrictPredicateInclusion
      ((tarskiAccumulatingCausalSystem patchable initial).stageMemory
        (initialCausalState patchable initial)
        word)
      (tarskiHistoricalMemory patchable initial) :=
  (tarskiAccumulatingCausalSystem patchable initial)
    |>.stageMemory_strictlyIncluded_historical
      (initialCausalState patchable initial)
      word

/-- Every current Tarski gap belongs positively to historical memory. -/
theorem tarskiCurrentGap_mem_historical
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (word : CausalAdditive.CausalWord) :
    tarskiHistoricalMemory
      patchable initial (tarskiHistoricalGap patchable initial word) :=
  (tarskiAccumulatingCausalSystem patchable initial)
    |>.historicalGap_mem_historical
      (initialCausalState patchable initial)
      word

/-- The generated Tarski gaps faithfully realize all causal words inside
historical memory. -/
theorem tarskiHistoricalGap_injective
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {left right : CausalAdditive.CausalWord}
    (sameGap :
      tarskiHistoricalGap patchable initial left =
        tarskiHistoricalGap patchable initial right) :
    left = right :=
  (tarskiAccumulatingCausalSystem patchable initial)
    |>.historicalGap_injective
      (initialCausalState patchable initial)
      sameGap

/-- The positive historical-gap realization is injective. -/
theorem tarskiRealizedHistoricalGap_injective
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {left right : CausalAdditive.CausalWord}
    (same :
      tarskiRealizedHistoricalGap patchable initial left =
        tarskiRealizedHistoricalGap patchable initial right) :
    left = right :=
  (tarskiAccumulatingCausalSystem patchable initial)
    |>.realizedHistoricalGap_injective
      (initialCausalState patchable initial)
      same

/-- No realized Tarski stage exhausts historical memory. -/
theorem tarskiNoStage_exhausts_historical
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (word : CausalAdditive.CausalWord)
    (exhausts :
      (tarskiAccumulatingCausalSystem patchable initial).ExhaustsHistorical
        (initialCausalState patchable initial)
        ((tarskiAccumulatingCausalSystem patchable initial).eval
          (initialCausalState patchable initial)
          word)) :
    False :=
  (tarskiAccumulatingCausalSystem patchable initial)
    |>.no_stage_exhausts_historical
      (initialCausalState patchable initial)
      word
      exhausts

/-! ## Closed Tarski theorem package -/

/-- Exact stepwise growth together with the generic historical-totality
theorem for every patchable Tarski context. -/
structure TarskiCumulativeTotalityTheorem
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    Type (max u v) where
  genericTotality :
    CausalAdditive.AccumulatingCausalSystem.CumulativeTotalityTheorem
      (tarskiAccumulatingCausalSystem patchable initial)
      (initialCausalState patchable initial)
  exactAdvance :
    (state : CausalState patchable initial) ->
    (sentence : patchable.context.Sentence) ->
      (tarskiAccumulatingCausalSystem patchable initial).Memory
          ((tarskiAccumulatingCausalSystem patchable initial).advance state)
          sentence ↔
        (tarskiAccumulatingCausalSystem patchable initial).Memory
            state sentence ∨
          sentence =
            (tarskiAccumulatingCausalSystem patchable initial).gap state

/-- Canonical cumulative-totality theorem of patchable Tarski repair. -/
def tarskiCumulativeTotalityTheorem
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    TarskiCumulativeTotalityTheorem patchable initial where
  genericTotality :=
    (tarskiAccumulatingCausalSystem patchable initial)
      |>.cumulativeTotalityTheorem
        (initialCausalState patchable initial)
  exactAdvance := tarskiAdvance_memory_iff patchable initial

end PatchableArithmeticTarskiContext
end ClosedStabilityTheorem
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.tarskiAdvance_memory_iff
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.tarskiStageMemory_strictlyIncluded_historical
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.tarskiHistoricalGap_injective
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.tarskiRealizedHistoricalGap_injective
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.tarskiNoStage_exhausts_historical
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.tarskiCumulativeTotalityTheorem
/- AXIOM_AUDIT_END -/
