import Meta.Core.CausalAdditiveNat
import Meta.Tarski.CausalOrbit

/-!
# Additive causal realization for every patchable Tarski context

This module instantiates the import-free accumulating causal system with the
positive Tarski memory already carried by `CausalState`.

The three abstract laws are not assumed as an external bridge:

* current-gap absence is the Tarski mismatch plus memory soundness;
* current-gap inscription is the canonical memory extension;
* previous-memory preservation is the intrinsic retention constructor.

Consequently, unary causal words act additively and faithfully on the Tarski
causal states.  The realized object carries zero, successor, commutative
addition, cancellation, and positive non-absorption.  `Nat` appears only via
the final comparison equivalence imported from `CausalAdditiveNat`.
-/

namespace Meta
namespace ClosedStabilityTheorem
namespace PatchableArithmeticTarskiContext

universe u v

/-! ## Closed accumulating system -/

/-- The causal state before any Tarski repair. -/
def initialCausalState
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    CausalState patchable initial where
  current := initial
  memory := CausalMemory.root

/--
Every patchable Tarski context is intrinsically an accumulating causal system.

No generic causal law is left as an uninstantiated premise.
-/
def tarskiAccumulatingCausalSystem
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    CausalAdditive.AccumulatingCausalSystem
      (CausalState patchable initial)
      patchable.context.Sentence where
  gap := fun state => patchable.diagonalSentence state.current
  Memory := fun state sentence =>
    CausalMemory.Remembers patchable initial state.memory sentence
  advance := CausalState.advance patchable initial
  gap_absent := by
    intro state
    exact CausalState.currentGap_not_remembered patchable initial state
  gap_inscribed := by
    intro state
    exact CausalState.advance_remembers_current_gap patchable initial state
  memory_preserved := by
    intro state sentence remembered
    exact
      CausalState.advance_remembers_previous
        patchable initial state remembered

/-! ## Intrinsic transcontextual Core transport -/

/--
The complete Core payload recomputed at a Tarski causal state.

It contains the current bilateral memory together with the formed and visible
transport chains generated by the current gap use.
-/
abbrev TarskiCausalStepTransportPayload
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (state : CausalState patchable initial) :=
  DynamicRelaxedUsage.DynamicGapCausalState
    (TarskiDynamicRelaxedUsage.tarskiPatchIntrinsicDynamicReturnFamily
      patchable initial)
    state.current

/-- The canonical complete Core payload at a Tarski causal state. -/
def tarskiCausalStepTransportPayload
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (state : CausalState patchable initial) :
    TarskiCausalStepTransportPayload patchable initial state :=
  DynamicRelaxedUsage.dynamicGapCausalState
    (TarskiDynamicRelaxedUsage.tarskiPatchIntrinsicDynamicReturnFamily
      patchable initial)
    state.current

/--
Dependent transport generated intrinsically from the complete Core payload at
each reached context.
-/
def tarskiCausalTransportStructure
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :=
  CausalAdditive.AccumulatingCausalSystem.causalTransportStructureOfPayload
    (tarskiAccumulatingCausalSystem patchable initial)
    (TarskiCausalStepTransportPayload patchable initial)
    (tarskiCausalStepTransportPayload patchable initial)

/-- Transport of one causal word from the initial Tarski state. -/
def tarskiCausalPathTransport
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (word : CausalAdditive.CausalWord) :=
  (tarskiCausalTransportStructure patchable initial).pathTransport
    (initialCausalState patchable initial)
    word

/--
Transcontextual composition of the transports of two additive causal words.

The second word is evaluated again from the state reached by the first, so its
concrete gaps and Core events are contextually re-instantiated.
-/
def tarskiComposedCausalPathTransport
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (left right : CausalAdditive.CausalWord) :=
  (tarskiCausalTransportStructure patchable initial).composedPathTransport
    (initialCausalState patchable initial)
    left
    right

/-! ## Word action on Tarski causal states -/

/-- The Tarski causal state realized by a causal word. -/
def causalWordState
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (word : CausalAdditive.CausalWord) :
    CausalState patchable initial :=
  (tarskiAccumulatingCausalSystem patchable initial).eval
    (initialCausalState patchable initial)
    word

/-- The global chronological transformation represented by a Tarski causal
word.  This is the additive target; raw causal states carry only the unary
operation `advance`. -/
def tarskiWordAction
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (word : CausalAdditive.CausalWord) :
    CausalAdditive.ChronologicalEndomorphism
      (CausalState patchable initial) :=
  (tarskiAccumulatingCausalSystem patchable initial).wordAction word

/-- Tarski word addition is pointwise chronological composition of the
corresponding global transformations. -/
theorem tarskiWordAction_add_at
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (left right : CausalAdditive.CausalWord)
    (state : CausalState patchable initial) :
    (tarskiWordAction
      patchable initial (CausalAdditive.CausalWord.add left right)).run state =
      (CausalAdditive.ChronologicalEndomorphism.compose
        (tarskiWordAction patchable initial left)
        (tarskiWordAction patchable initial right)).run state :=
  (tarskiAccumulatingCausalSystem patchable initial).wordAction_add_at
    left right state

/-- The transformation representation is faithful under pointwise equality. -/
theorem tarskiWordAction_pointwiseFaithful
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {left right : CausalAdditive.CausalWord}
    (sameAction :
      (state : CausalState patchable initial) ->
        (tarskiWordAction patchable initial left).run state =
          (tarskiWordAction patchable initial right).run state) :
    left = right :=
  (tarskiAccumulatingCausalSystem patchable initial)
    |>.wordAction_pointwise_faithful
      (initialCausalState patchable initial)
      sameAction

/-- The empty word realizes the initial causal state. -/
theorem causalWordState_zero
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    causalWordState patchable initial CausalAdditive.CausalWord.zero =
      initialCausalState patchable initial :=
  rfl

/-- Word successor realizes exactly one canonical Tarski advance. -/
theorem causalWordState_succ
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (word : CausalAdditive.CausalWord) :
    causalWordState patchable initial (CausalAdditive.CausalWord.succ word) =
      CausalState.advance
        patchable
        initial
        (causalWordState patchable initial word) :=
  rfl

/-- Tarski word addition is chronological composition of causal transitions. -/
theorem causalWordState_add
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (left right : CausalAdditive.CausalWord) :
    causalWordState
        patchable initial (CausalAdditive.CausalWord.add left right) =
      (tarskiAccumulatingCausalSystem patchable initial).eval
        (causalWordState patchable initial left)
        right :=
  (tarskiAccumulatingCausalSystem patchable initial).eval_add
    (initialCausalState patchable initial)
    left
    right

/-- Existing Tarski memory equivalence induces the abstract memory equivalence. -/
def abstractMemoryEquivalentOfTarski
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {left right : CausalState patchable initial}
    (equivalent : MemoryEquivalent left right) :
    CausalAdditive.AccumulatingCausalSystem.MemoryEquivalent
      (tarskiAccumulatingCausalSystem patchable initial)
      left
      right where
  forward := equivalent.forward
  backward := equivalent.backward

/-- Distinct words cannot have extensionally equivalent Tarski memories. -/
theorem causalWordState_memoryFaithful
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {left right : CausalAdditive.CausalWord}
    (equivalent :
      MemoryEquivalent
        (causalWordState patchable initial left)
        (causalWordState patchable initial right)) :
    left = right :=
  (tarskiAccumulatingCausalSystem patchable initial).eval_faithful
    (initialCausalState patchable initial)
    (abstractMemoryEquivalentOfTarski patchable initial equivalent)

/-- Distinct words cannot have causally equivalent Tarski realizations. -/
theorem causalWordState_causallyFaithful
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {left right : CausalAdditive.CausalWord}
    (equivalent :
      CausallyEquivalent
        (causalWordState patchable initial left)
        (causalWordState patchable initial right)) :
    left = right :=
  causalWordState_memoryFaithful
    patchable initial equivalent.sameMemory

/-- Raw equality of realized Tarski states determines the causal word. -/
theorem causalWordState_injective
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {left right : CausalAdditive.CausalWord}
    (sameState :
      causalWordState patchable initial left =
        causalWordState patchable initial right) :
    left = right :=
  (tarskiAccumulatingCausalSystem patchable initial).eval_injective
    (initialCausalState patchable initial)
    sameState

/-- Every nonempty word is separated from its Tarski source by the source gap. -/
theorem causalWordState_noPositiveReturn
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (word : CausalAdditive.CausalWord)
    (nonzero : word = CausalAdditive.CausalWord.zero -> False)
    (equivalent :
      MemoryEquivalent
        (initialCausalState patchable initial)
        (causalWordState patchable initial word)) :
    False :=
  (tarskiAccumulatingCausalSystem patchable initial)
    |>.no_memoryEquivalent_forward_of_nonzero
      (initialCausalState patchable initial)
      word
      nonzero
      (abstractMemoryEquivalentOfTarski patchable initial equivalent)

/-! ## Positive realized Tarski naturals -/

/-- The positive realized causal-natural object of a patchable Tarski orbit. -/
abbrev TarskiRealizedCausalNat
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :=
  CausalAdditive.AccumulatingCausalSystem.RealizedCausalNat
    (tarskiAccumulatingCausalSystem patchable initial)
    (initialCausalState patchable initial)

/-- Realized Tarski zero. -/
def tarskiRealizedZero
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    TarskiRealizedCausalNat patchable initial :=
  CausalAdditive.AccumulatingCausalSystem.RealizedCausalNat.zero

/-- Realized Tarski successor. -/
def tarskiRealizedSucc
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (realized : TarskiRealizedCausalNat patchable initial) :
    TarskiRealizedCausalNat patchable initial :=
  CausalAdditive.AccumulatingCausalSystem.RealizedCausalNat.succ realized

/-- Realized Tarski addition. -/
def tarskiRealizedAdd
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (left right : TarskiRealizedCausalNat patchable initial) :
    TarskiRealizedCausalNat patchable initial :=
  CausalAdditive.AccumulatingCausalSystem.RealizedCausalNat.add left right

/-- The state of a realized Tarski sum is chronological causal evaluation. -/
theorem tarskiRealizedAdd_state
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (left right : TarskiRealizedCausalNat patchable initial) :
    (tarskiRealizedAdd patchable initial left right).state =
      (tarskiAccumulatingCausalSystem patchable initial).eval
        left.state
        right.word :=
  CausalAdditive.AccumulatingCausalSystem.RealizedCausalNat.state_add
    left right

/-- Realized Tarski addition is associative. -/
theorem tarskiRealizedAdd_associative
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (left middle right : TarskiRealizedCausalNat patchable initial) :
    tarskiRealizedAdd patchable initial
        (tarskiRealizedAdd patchable initial left middle) right =
      tarskiRealizedAdd patchable initial left
        (tarskiRealizedAdd patchable initial middle right) :=
  CausalAdditive.AccumulatingCausalSystem.RealizedCausalNat.add_associative
    left middle right

/-- Realized Tarski addition is commutative. -/
theorem tarskiRealizedAdd_commutative
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (left right : TarskiRealizedCausalNat patchable initial) :
    tarskiRealizedAdd patchable initial left right =
      tarskiRealizedAdd patchable initial right left :=
  CausalAdditive.AccumulatingCausalSystem.RealizedCausalNat.add_commutative
    left right

/-- Realized Tarski addition has constructive right cancellation. -/
theorem tarskiRealizedAdd_right_cancel
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {left right suffix : TarskiRealizedCausalNat patchable initial}
    (same :
      tarskiRealizedAdd patchable initial left suffix =
        tarskiRealizedAdd patchable initial right suffix) :
    left = right :=
  CausalAdditive.AccumulatingCausalSystem.RealizedCausalNat.add_right_cancel
    same

/-- Realized Tarski addition has constructive left cancellation. -/
theorem tarskiRealizedAdd_left_cancel
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {base left right : TarskiRealizedCausalNat patchable initial}
    (same :
      tarskiRealizedAdd patchable initial base left =
        tarskiRealizedAdd patchable initial base right) :
    left = right :=
  CausalAdditive.AccumulatingCausalSystem.RealizedCausalNat.add_left_cancel
    same

/-- No nonempty realized Tarski increment can be absorbed. -/
theorem tarskiRealizedAdd_noPositiveAbsorption
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (realized : TarskiRealizedCausalNat patchable initial)
    (word : CausalAdditive.CausalWord)
    (nonzero : word = CausalAdditive.CausalWord.zero -> False)
    (absorbed :
      tarskiRealizedAdd
          patchable
          initial
          realized
          (CausalAdditive.AccumulatingCausalSystem.RealizedCausalNat.embed word) =
        realized) :
    False :=
  CausalAdditive.AccumulatingCausalSystem.RealizedCausalNat.no_positive_absorption
    realized word nonzero absorbed

/-- Causal equivalence of realized Tarski states determines their words. -/
theorem tarskiRealizedState_causallyDeterminesWord
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (left right : TarskiRealizedCausalNat patchable initial)
    (equivalent : CausallyEquivalent left.state right.state) :
    left.word = right.word := by
  apply
    CausalAdditive.AccumulatingCausalSystem.RealizedCausalNat.memoryEquivalent_determines_word
      left right
  exact
    abstractMemoryEquivalentOfTarski
      patchable initial equivalent.sameMemory

/-- Causal equivalence of realized states determines the complete objects. -/
theorem tarskiRealizedState_causallyFaithful
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (left right : TarskiRealizedCausalNat patchable initial)
    (equivalent : CausallyEquivalent left.state right.state) :
    left = right := by
  apply
    CausalAdditive.AccumulatingCausalSystem.RealizedCausalNat.memoryEquivalent_determines
      left right
  exact
    abstractMemoryEquivalentOfTarski
      patchable initial equivalent.sameMemory

/-! ## Closed theorem package -/

/--
The additive causal realization theorem closed over a patchable Tarski context.
-/
structure TarskiCausalAdditiveRealizationTheorem
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    Type (max u v) where
  transformationAdditive :
    (left right : CausalAdditive.CausalWord) ->
    (state : CausalState patchable initial) ->
      (tarskiWordAction
        patchable initial (CausalAdditive.CausalWord.add left right)).run state =
        (CausalAdditive.ChronologicalEndomorphism.compose
          (tarskiWordAction patchable initial left)
          (tarskiWordAction patchable initial right)).run state
  transformationFaithful :
    {left right : CausalAdditive.CausalWord} ->
      ((state : CausalState patchable initial) ->
        (tarskiWordAction patchable initial left).run state =
          (tarskiWordAction patchable initial right).run state) ->
        left = right
  actionAdditive :
    (left right : CausalAdditive.CausalWord) ->
      causalWordState
          patchable initial (CausalAdditive.CausalWord.add left right) =
        (tarskiAccumulatingCausalSystem patchable initial).eval
          (causalWordState patchable initial left)
          right
  actionFaithful :
    {left right : CausalAdditive.CausalWord} ->
      CausallyEquivalent
          (causalWordState patchable initial left)
          (causalWordState patchable initial right) ->
        left = right
  realizedStateAdditive :
    (left right : TarskiRealizedCausalNat patchable initial) ->
      (tarskiRealizedAdd patchable initial left right).state =
        (tarskiAccumulatingCausalSystem patchable initial).eval
          left.state
          right.word
  realizedAssociative :
    (left middle right : TarskiRealizedCausalNat patchable initial) ->
      tarskiRealizedAdd patchable initial
          (tarskiRealizedAdd patchable initial left middle) right =
        tarskiRealizedAdd patchable initial left
          (tarskiRealizedAdd patchable initial middle right)
  realizedCommutative :
    (left right : TarskiRealizedCausalNat patchable initial) ->
      tarskiRealizedAdd patchable initial left right =
        tarskiRealizedAdd patchable initial right left
  realizedStateFaithful :
    (left right : TarskiRealizedCausalNat patchable initial) ->
      CausallyEquivalent left.state right.state ->
        left = right
  realizedNoPositiveAbsorption :
    (realized : TarskiRealizedCausalNat patchable initial) ->
    (word : CausalAdditive.CausalWord) ->
      (word = CausalAdditive.CausalWord.zero -> False) ->
        tarskiRealizedAdd
            patchable
            initial
            realized
            (CausalAdditive.AccumulatingCausalSystem.RealizedCausalNat.embed
              word) = realized ->
          False

/-- Canonical closed additive realization of every patchable Tarski context. -/
def tarskiCausalAdditiveRealizationTheorem
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    TarskiCausalAdditiveRealizationTheorem patchable initial where
  transformationAdditive := tarskiWordAction_add_at patchable initial
  transformationFaithful :=
    tarskiWordAction_pointwiseFaithful patchable initial
  actionAdditive := causalWordState_add patchable initial
  actionFaithful := causalWordState_causallyFaithful patchable initial
  realizedStateAdditive := tarskiRealizedAdd_state patchable initial
  realizedAssociative := tarskiRealizedAdd_associative patchable initial
  realizedCommutative := tarskiRealizedAdd_commutative patchable initial
  realizedStateFaithful :=
    tarskiRealizedState_causallyFaithful patchable initial
  realizedNoPositiveAbsorption :=
    tarskiRealizedAdd_noPositiveAbsorption patchable initial

end PatchableArithmeticTarskiContext
end ClosedStabilityTheorem
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.tarskiAccumulatingCausalSystem
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.tarskiComposedCausalPathTransport
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.tarskiWordAction_add_at
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.tarskiWordAction_pointwiseFaithful
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.causalWordState_add
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.causalWordState_causallyFaithful
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.tarskiRealizedAdd_state
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.tarskiRealizedState_causallyFaithful
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.tarskiCausalAdditiveRealizationTheorem
/- AXIOM_AUDIT_END -/
