import Meta.Tarski.CausalMemory

/-!
# Causal states and non-return for generic Tarski patching

The current syntactic candidate is paired with the positive memory of the
events that reached it.  Causal equivalence is extensional: it preserves both
pointwise visible behaviour and the collection of remembered diagonal
obligations.

The separation proof does not use candidate injectivity, diagonal-index
injectivity, raw state equality, or memory length.  The current challenge is
absent by the local mismatch and becomes present after the next repair.
-/

namespace Meta
namespace ClosedStabilityTheorem
namespace PatchableArithmeticTarskiContext

universe u v

/-! ## Intrinsic causal state and transition -/

/-- A current syntactic candidate together with its coherent causal memory. -/
structure CausalState
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    Type (max u v) where
  current : patchable.context.Predicate
  memory : CausalMemory patchable initial current

namespace CausalState

/--
Extend a causal state with the canonical algorithmic step generated by its
current diagonal mismatch.
-/
def advance
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (state : CausalState patchable initial) :
    CausalState patchable initial :=
  let event := patchable.step state.current
  { current := event.nextPredicate
    memory := CausalMemory.extend state.memory event }

/-- Causal advance has exactly the intrinsic syntax-level successor. -/
theorem advance_current_eq_nextPredicate
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (state : CausalState patchable initial) :
    (advance patchable initial state).current =
      patchable.nextPredicate state.current :=
  rfl

/-- Causal advance is the already authorized gap-driven dynamic transition. -/
theorem advance_current_eq_gapDrivenNext
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (state : CausalState patchable initial) :
    (advance patchable initial state).current =
      (TarskiDynamicRelaxedUsage.tarskiPatchGapDrivenDynamicSystem
        patchable
        initial).next state.current :=
  (advance_current_eq_nextPredicate patchable initial state).trans
    (TarskiDynamicRelaxedUsage.tarskiPatchNext_eq_nextPredicate
      patchable
      initial
      state.current).symm

/-- The gap repaired by a causal advance is now positively remembered. -/
theorem advance_remembers_current_gap
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (state : CausalState patchable initial) :
    CausalMemory.Remembers
      patchable
      initial
      (advance patchable initial state).memory
      (patchable.diagonalSentence state.current) := by
  exact Or.inl rfl

/-- Every previous memory witness survives one causal advance. -/
theorem advance_remembers_previous
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (state : CausalState patchable initial)
    {sentence : patchable.context.Sentence}
    (remembered :
      CausalMemory.Remembers
        patchable
        initial
        state.memory
        sentence) :
    CausalMemory.Remembers
      patchable
      initial
      (advance patchable initial state).memory
      sentence := by
  exact Or.inr remembered

/-- A state's current diagonal challenge is absent from its own memory. -/
theorem currentGap_not_remembered
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (state : CausalState patchable initial) :
    CausalMemory.Remembers
        patchable
        initial
        state.memory
        (patchable.diagonalSentence state.current) ->
      False :=
  CausalMemory.current_not_remembered
    patchable
    initial
    state.memory

end CausalState

/-! ## Canonical causal orbit and alignment -/

/-- The canonical orbit of complete causal states. -/
def causalOrbit
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    Nat -> CausalState patchable initial
  | 0 =>
      { current := initial
        memory := CausalMemory.root }
  | Nat.succ n =>
      CausalState.advance patchable initial (causalOrbit patchable initial n)

/-- The current component is exactly the existing generic syntax orbit. -/
theorem causalOrbit_current_eq_genericOrbitCandidate
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (n : Nat) :
    (causalOrbit patchable initial n).current =
      genericOrbitCandidate patchable initial n := by
  induction n with
  | zero =>
      rfl
  | succ n inductionHypothesis =>
      change
        patchable.nextPredicate
            (causalOrbit patchable initial n).current =
          patchable.nextPredicate
            (genericOrbitCandidate patchable initial n)
      exact congrArg patchable.nextPredicate inductionHypothesis

/-- The current component is also exactly the gap-driven dynamic orbit. -/
theorem causalOrbit_current_eq_genericDynamicOrbitCandidate
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (n : Nat) :
    (causalOrbit patchable initial n).current =
      genericDynamicOrbitCandidate patchable initial n :=
  (causalOrbit_current_eq_genericOrbitCandidate patchable initial n).trans
    (genericDynamicOrbitCandidate_eq_genericOrbitCandidate
      patchable
      initial
      n).symm

/-- Every challenge strictly earlier than a state occurs in its memory. -/
theorem causalOrbit_remembers_of_lt
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {k n : Nat}
    (earlier : k < n) :
    CausalMemory.Remembers
      patchable
      initial
      (causalOrbit patchable initial n).memory
      (genericOrbitIndex patchable initial k) := by
  induction n with
  | zero =>
      exact (Nat.not_lt_zero k earlier).elim
  | succ n inductionHypothesis =>
      have bounded : k <= n := Nat.le_of_lt_succ earlier
      cases Nat.eq_or_lt_of_le bounded with
      | inl currentIndex =>
          subst k
          have rememberedCurrent :=
            CausalState.advance_remembers_current_gap
              patchable
              initial
              (causalOrbit patchable initial n)
          have sameChallenge :
              patchable.diagonalSentence
                  (causalOrbit patchable initial n).current =
                genericOrbitIndex patchable initial n :=
            congrArg
              patchable.diagonalSentence
              (causalOrbit_current_eq_genericOrbitCandidate
                patchable initial n)
          rw [sameChallenge] at rememberedCurrent
          exact rememberedCurrent
      | inr strictlyEarlier =>
          exact
            CausalState.advance_remembers_previous
              patchable
              initial
              (causalOrbit patchable initial n)
              (inductionHypothesis strictlyEarlier)

/-- The current orbit challenge is not among that state's past obligations. -/
theorem causalOrbit_currentIndex_not_remembered
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (n : Nat) :
    CausalMemory.Remembers
        patchable
        initial
        (causalOrbit patchable initial n).memory
        (genericOrbitIndex patchable initial n) ->
      False := by
  intro remembered
  apply
    CausalState.currentGap_not_remembered
      patchable
      initial
      (causalOrbit patchable initial n)
  have sameChallenge :
      genericOrbitIndex patchable initial n =
        patchable.diagonalSentence
          (causalOrbit patchable initial n).current :=
    congrArg
      patchable.diagonalSentence
      (causalOrbit_current_eq_genericOrbitCandidate
        patchable initial n).symm
  rw [← sameChallenge]
  exact remembered

/-! ## Extensional memory and causal equivalence -/

/-- Two states retain exactly the same causal obligations. -/
structure MemoryEquivalent
    {patchable : PatchableArithmeticTarskiContext.{u, v}}
    {initial : patchable.context.Predicate}
    (left right : CausalState patchable initial) :
    Prop where
  forward :
    (sentence : patchable.context.Sentence) ->
      CausalMemory.Remembers
          patchable initial left.memory sentence ->
        CausalMemory.Remembers
          patchable initial right.memory sentence
  backward :
    (sentence : patchable.context.Sentence) ->
      CausalMemory.Remembers
          patchable initial right.memory sentence ->
        CausalMemory.Remembers
          patchable initial left.memory sentence

/-- Reflexivity of extensional causal memory. -/
def memoryEquivalentRefl
    {patchable : PatchableArithmeticTarskiContext.{u, v}}
    {initial : patchable.context.Predicate}
    (state : CausalState patchable initial) :
    MemoryEquivalent state state where
  forward := by
    intro _ remembered
    exact remembered
  backward := by
    intro _ remembered
    exact remembered

/-- Symmetry of extensional causal memory. -/
def MemoryEquivalent.symm
    {patchable : PatchableArithmeticTarskiContext.{u, v}}
    {initial : patchable.context.Predicate}
    {left right : CausalState patchable initial}
    (equivalent : MemoryEquivalent left right) :
    MemoryEquivalent right left where
  forward := equivalent.backward
  backward := equivalent.forward

/-- Transitivity of extensional causal memory. -/
def MemoryEquivalent.trans
    {patchable : PatchableArithmeticTarskiContext.{u, v}}
    {initial : patchable.context.Predicate}
    {left middle right : CausalState patchable initial}
    (leftMiddle : MemoryEquivalent left middle)
    (middleRight : MemoryEquivalent middle right) :
    MemoryEquivalent left right where
  forward := by
    intro sentence remembered
    exact
      middleRight.forward sentence
        (leftMiddle.forward sentence remembered)
  backward := by
    intro sentence remembered
    exact
      leftMiddle.backward sentence
        (middleRight.backward sentence remembered)

/--
Causal equivalence preserves all pointwise visible responses and all
remembered obligations, while ignoring proof terms and concrete memory shape.
-/
structure CausallyEquivalent
    {patchable : PatchableArithmeticTarskiContext.{u, v}}
    {initial : patchable.context.Predicate}
    (left right : CausalState patchable initial) :
    Prop where
  sameVisibleBehavior :
    (sentence : patchable.context.Sentence) ->
      patchable.truthAt left.current sentence ↔
        patchable.truthAt right.current sentence
  sameMemory : MemoryEquivalent left right

/-- Reflexivity of complete causal equivalence. -/
def causallyEquivalentRefl
    {patchable : PatchableArithmeticTarskiContext.{u, v}}
    {initial : patchable.context.Predicate}
    (state : CausalState patchable initial) :
    CausallyEquivalent state state where
  sameVisibleBehavior := by
    intro _
    exact Iff.rfl
  sameMemory := memoryEquivalentRefl state

/-- Symmetry of complete causal equivalence. -/
def CausallyEquivalent.symm
    {patchable : PatchableArithmeticTarskiContext.{u, v}}
    {initial : patchable.context.Predicate}
    {left right : CausalState patchable initial}
    (equivalent : CausallyEquivalent left right) :
    CausallyEquivalent right left where
  sameVisibleBehavior := by
    intro sentence
    exact (equivalent.sameVisibleBehavior sentence).symm
  sameMemory := equivalent.sameMemory.symm

/-- Transitivity of complete causal equivalence. -/
def CausallyEquivalent.trans
    {patchable : PatchableArithmeticTarskiContext.{u, v}}
    {initial : patchable.context.Predicate}
    {left middle right : CausalState patchable initial}
    (leftMiddle : CausallyEquivalent left middle)
    (middleRight : CausallyEquivalent middle right) :
    CausallyEquivalent left right where
  sameVisibleBehavior := by
    intro sentence
    exact
      (leftMiddle.sameVisibleBehavior sentence).trans
        (middleRight.sameVisibleBehavior sentence)
  sameMemory := leftMiddle.sameMemory.trans middleRight.sameMemory

/-! ## Non-return caused by accumulated memory -/

/--
Strictly later orbit states already differ extensionally in causal memory.

The separating witness is the earlier state's current diagonal challenge: it
is absent there by mismatch and present later by positive accumulation.
-/
theorem causalOrbit_memory_notEquivalent_of_lt
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {n m : Nat}
    (later : n < m)
    (equivalent :
      MemoryEquivalent
        (causalOrbit patchable initial n)
        (causalOrbit patchable initial m)) :
    False :=
  causalOrbit_currentIndex_not_remembered
    patchable
    initial
    n
    (equivalent.backward
      (genericOrbitIndex patchable initial n)
      (causalOrbit_remembers_of_lt patchable initial later))

/-- No strictly later orbit state is causally equivalent to an earlier one. -/
theorem causalOrbit_not_causallyEquivalent_of_lt
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {n m : Nat}
    (later : n < m)
    (equivalent :
      CausallyEquivalent
        (causalOrbit patchable initial n)
        (causalOrbit patchable initial m)) :
    False :=
  causalOrbit_memory_notEquivalent_of_lt
    patchable
    initial
    later
    equivalent.sameMemory

/-- No causal orbit has a positive period modulo causal equivalence. -/
theorem causalOrbit_noPositivePeriod
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (n period : Nat)
    (positivePeriod : 0 < period)
    (equivalent :
      CausallyEquivalent
        (causalOrbit patchable initial n)
        (causalOrbit patchable initial (n + period))) :
    False :=
  causalOrbit_not_causallyEquivalent_of_lt
    patchable
    initial
    (Nat.lt_add_of_pos_right positivePeriod)
    equivalent

end PatchableArithmeticTarskiContext
end ClosedStabilityTheorem
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.CausalState
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.CausalState.advance
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.causalOrbit
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.causalOrbit_remembers_of_lt
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.MemoryEquivalent
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.CausallyEquivalent
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.causalOrbit_memory_notEquivalent_of_lt
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.causalOrbit_not_causallyEquivalent_of_lt
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.causalOrbit_noPositivePeriod
/- AXIOM_AUDIT_END -/
