import Meta.Tarski.DynamicRelaxedUsage

/-!
# Generic orbit of intrinsic Tarski patching

This file proves that non-return is not a peculiarity of the concrete finite
support model.  In every patchable Tarski context, the local diagonal mismatch,
the repair of the current index, and preservation away from that index force
all later diagonal challenges and candidates to remain distinct.

The proof uses no externally supplied rank, freshness oracle, transition map,
or terminal bridge.  Freshness is derived simultaneously with cumulative
agreement from the intrinsic patch operation.
-/

namespace Meta
namespace ClosedStabilityTheorem
namespace PatchableArithmeticTarskiContext

universe u v

/-! ## Generic syntax and dynamic orbits -/

/-- The syntactic candidate reached after `n` intrinsic repairs. -/
def genericOrbitCandidate
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (n : Nat) :
    patchable.context.Predicate :=
  patchable.iteratePredicate n initial

/-- The diagonal challenge generated by the candidate at step `n`. -/
def genericOrbitIndex
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (n : Nat) :
    patchable.context.Sentence :=
  patchable.diagonalSentence
    (genericOrbitCandidate patchable initial n)

/-- The candidate reached by the gap-driven dynamic system after `n` steps. -/
def genericDynamicOrbitCandidate
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (n : Nat) :
    patchable.context.Predicate :=
  (TarskiDynamicRelaxedUsage.tarskiPatchGapDrivenDynamicSystem
      patchable
      initial).iterateSource n initial

/-- Dynamic and syntax-level candidates coincide at every step. -/
theorem genericDynamicOrbitCandidate_eq_genericOrbitCandidate
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (n : Nat) :
    genericDynamicOrbitCandidate patchable initial n =
      genericOrbitCandidate patchable initial n :=
  TarskiDynamicRelaxedUsage.tarskiPatchIterate_eq_iteratePredicate
    patchable
    initial
    initial
    n

/-! ## Intrinsic cumulative invariant -/

/-- A candidate agrees with semantics at a selected sentence. -/
def CorrectAt
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (candidate : patchable.context.Predicate)
    (sentence : patchable.context.Sentence) :
    Prop :=
  patchable.truthAt candidate sentence ↔
    patchable.context.models sentence

/--
The intrinsic invariant at step `n`.

Every earlier diagonal challenge is still repaired, and every earlier
challenge is distinct from the current one.  The two fields are constructed
together: preservation carries old repairs forward, while the current local
mismatch forces the next challenge to be fresh relative to all those repairs.
-/
structure GenericOrbitInvariant
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (n : Nat) :
    Type (max u v) where
  cumulativeAgreement :
    (k : Nat) ->
      k < n ->
        CorrectAt
          patchable
          (genericOrbitCandidate patchable initial n)
          (genericOrbitIndex patchable initial k)
  currentFresh :
    (k : Nat) ->
      k < n ->
        genericOrbitIndex patchable initial k =
          genericOrbitIndex patchable initial n ->
            False

/--
Canonical invariant of every generic patch orbit.

The successor case first transports all previous corrections through the
off-index preservation law and adds the correction made by the current patch.
The diagonal mismatch of the new candidate then proves that its challenge
cannot be any previously repaired challenge.
-/
def genericOrbitInvariant
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    (n : Nat) -> GenericOrbitInvariant patchable initial n
  | 0 =>
      { cumulativeAgreement := by
          intro k impossible
          exact (Nat.not_lt_zero k impossible).elim
        currentFresh := by
          intro k impossible
          exact (Nat.not_lt_zero k impossible).elim }
  | Nat.succ n => by
      let previous := genericOrbitInvariant patchable initial n
      let current := genericOrbitCandidate patchable initial n
      let currentStep := patchable.step current
      have agreement :
          (k : Nat) ->
            k < Nat.succ n ->
              CorrectAt
                patchable
                (genericOrbitCandidate patchable initial (Nat.succ n))
                (genericOrbitIndex patchable initial k) := by
        intro k earlier
        have bounded : k <= n := Nat.le_of_lt_succ earlier
        cases Nat.eq_or_lt_of_le bounded with
        | inl currentIndex =>
            cases currentIndex
            exact currentStep.repaired_index_agreement
        | inr strictlyEarlier =>
            exact
              (currentStep.preserves_off_index
                (genericOrbitIndex patchable initial k)
                (previous.currentFresh k strictlyEarlier)).trans
                (previous.cumulativeAgreement k strictlyEarlier)
      exact
        { cumulativeAgreement := agreement
          currentFresh := by
            intro k earlier sameIndex
            have repairedCurrent :
                CorrectAt
                  patchable
                  (genericOrbitCandidate patchable initial (Nat.succ n))
                  (genericOrbitIndex patchable initial (Nat.succ n)) := by
              rw [← sameIndex]
              exact agreement k earlier
            exact
              tarski_local_mismatch
                (patchable.context.fixedPoint
                  (genericOrbitCandidate patchable initial (Nat.succ n)))
                repairedCurrent }

/-! ## Generic cumulative agreement and freshness -/

/-- Every later candidate remains correct at every earlier challenge. -/
theorem genericOrbit_cumulativeAgreement
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {k n : Nat}
    (earlier : k < n) :
    CorrectAt
      patchable
      (genericOrbitCandidate patchable initial n)
      (genericOrbitIndex patchable initial k) :=
  (genericOrbitInvariant patchable initial n).cumulativeAgreement k earlier

/-- The current challenge is distinct from every earlier challenge. -/
theorem genericOrbitIndex_ne_of_lt
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {k n : Nat}
    (earlier : k < n) :
    genericOrbitIndex patchable initial k =
      genericOrbitIndex patchable initial n ->
        False :=
  (genericOrbitInvariant patchable initial n).currentFresh k earlier

/-- The current candidate cannot already be correct at its own challenge. -/
theorem genericOrbit_currentMismatch
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (n : Nat) :
    CorrectAt
        patchable
        (genericOrbitCandidate patchable initial n)
        (genericOrbitIndex patchable initial n) ->
      False :=
  tarski_local_mismatch
    (patchable.context.fixedPoint
      (genericOrbitCandidate patchable initial n))

/-! ## Injectivity and absence of return -/

/-- The generic diagonal challenges determine their iteration indices. -/
theorem genericOrbitIndex_injective
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {k n : Nat}
    (sameIndex :
      genericOrbitIndex patchable initial k =
        genericOrbitIndex patchable initial n) :
    k = n := by
  cases Nat.lt_trichotomy k n with
  | inl earlier =>
      exact
        (genericOrbitIndex_ne_of_lt
          patchable initial earlier sameIndex).elim
  | inr notEarlier =>
      cases notEarlier with
      | inl same =>
          exact same
      | inr later =>
          exact
            (genericOrbitIndex_ne_of_lt
              patchable initial later sameIndex.symm).elim

/-- The generic syntactic candidates determine their iteration indices. -/
theorem genericOrbitCandidate_injective
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {k n : Nat}
    (sameCandidate :
      genericOrbitCandidate patchable initial k =
        genericOrbitCandidate patchable initial n) :
    k = n :=
  genericOrbitIndex_injective
    patchable
    initial
    (congrArg (patchable.diagonalSentence) sameCandidate)

/-- The gap-driven dynamic candidates determine their iteration indices. -/
theorem genericDynamicOrbitCandidate_injective
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    {k n : Nat}
    (sameCandidate :
      genericDynamicOrbitCandidate patchable initial k =
        genericDynamicOrbitCandidate patchable initial n) :
    k = n := by
  apply genericOrbitCandidate_injective patchable initial
  rw [← genericDynamicOrbitCandidate_eq_genericOrbitCandidate
    patchable initial k]
  rw [← genericDynamicOrbitCandidate_eq_genericOrbitCandidate
    patchable initial n]
  exact sameCandidate

/-- Constructive left cancellation for addition. -/
theorem generic_nat_add_left_cancel
    {base left right : Nat}
    (sameSum : base + left = base + right) :
    left = right := by
  induction base with
  | zero =>
      rw [Nat.zero_add, Nat.zero_add] at sameSum
      exact sameSum
  | succ base inductionHypothesis =>
      rw [Nat.succ_add, Nat.succ_add] at sameSum
      exact inductionHypothesis (Nat.succ.inj sameSum)

/-- No generic syntax-level patch orbit has a positive exact period. -/
theorem genericOrbit_noExactReturn
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (n period : Nat)
    (positivePeriod : 0 < period)
    (sameCandidate :
      genericOrbitCandidate patchable initial (n + period) =
        genericOrbitCandidate patchable initial n) :
    False := by
  have sameIteration : n + period = n :=
    genericOrbitCandidate_injective patchable initial sameCandidate
  have period_eq_zero : period = 0 := by
    apply generic_nat_add_left_cancel (base := n)
    exact sameIteration.trans (Nat.add_zero n).symm
  cases period_eq_zero
  exact Nat.lt_irrefl 0 positivePeriod

/-- No generic gap-driven dynamic patch orbit has a positive exact period. -/
theorem genericDynamicOrbit_noExactReturn
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (n period : Nat)
    (positivePeriod : 0 < period)
    (sameCandidate :
      genericDynamicOrbitCandidate patchable initial (n + period) =
        genericDynamicOrbitCandidate patchable initial n) :
    False := by
  have sameIteration : n + period = n :=
    genericDynamicOrbitCandidate_injective
      patchable initial sameCandidate
  have period_eq_zero : period = 0 := by
    apply generic_nat_add_left_cancel (base := n)
    exact sameIteration.trans (Nat.add_zero n).symm
  cases period_eq_zero
  exact Nat.lt_irrefl 0 positivePeriod

/-- Every candidate on the generic orbit remains globally incomplete. -/
theorem genericOrbit_everyCandidateIncomplete
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate)
    (n : Nat)
    (definition :
      TarskiTruthDefinition
        (patchable.truthAt (genericOrbitCandidate patchable initial n))
        patchable.context.models) :
    False :=
  patchable.truthAt_notGloballyCorrect
    (genericOrbitCandidate patchable initial n)
    definition

/-! ## Closed generic orbit package -/

/--
All global consequences of intrinsic Tarski patching, uniformly over every
patchable syntax and with no model-specific freshness construction.
-/
structure GenericPatchOrbitTheorem
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    Type (max u v) where
  cumulativeAgreement :
    forall {k n : Nat},
      k < n ->
        CorrectAt
          patchable
          (genericOrbitCandidate patchable initial n)
          (genericOrbitIndex patchable initial k)
  currentMismatch :
    forall n : Nat,
      CorrectAt
          patchable
          (genericOrbitCandidate patchable initial n)
          (genericOrbitIndex patchable initial n) ->
        False
  indicesSeparated :
    forall {k n : Nat},
      genericOrbitIndex patchable initial k =
          genericOrbitIndex patchable initial n ->
        k = n
  syntaxOrbitSeparated :
    forall {k n : Nat},
      genericOrbitCandidate patchable initial k =
          genericOrbitCandidate patchable initial n ->
        k = n
  dynamicOrbitSeparated :
    forall {k n : Nat},
      genericDynamicOrbitCandidate patchable initial k =
          genericDynamicOrbitCandidate patchable initial n ->
        k = n
  syntaxNoExactReturn :
    forall n period : Nat,
      0 < period ->
        genericOrbitCandidate patchable initial (n + period) =
            genericOrbitCandidate patchable initial n ->
          False
  dynamicNoExactReturn :
    forall n period : Nat,
      0 < period ->
        genericDynamicOrbitCandidate patchable initial (n + period) =
            genericDynamicOrbitCandidate patchable initial n ->
          False
  everyCandidateIncomplete :
    forall n : Nat,
      TarskiTruthDefinition
          (patchable.truthAt (genericOrbitCandidate patchable initial n))
          patchable.context.models ->
        False

/-- Canonical generic theorem for every intrinsic Tarski patch orbit. -/
def genericPatchOrbitTheorem
    (patchable : PatchableArithmeticTarskiContext.{u, v})
    (initial : patchable.context.Predicate) :
    GenericPatchOrbitTheorem patchable initial where
  cumulativeAgreement :=
    genericOrbit_cumulativeAgreement patchable initial
  currentMismatch := genericOrbit_currentMismatch patchable initial
  indicesSeparated := genericOrbitIndex_injective patchable initial
  syntaxOrbitSeparated :=
    genericOrbitCandidate_injective patchable initial
  dynamicOrbitSeparated :=
    genericDynamicOrbitCandidate_injective patchable initial
  syntaxNoExactReturn := genericOrbit_noExactReturn patchable initial
  dynamicNoExactReturn :=
    genericDynamicOrbit_noExactReturn patchable initial
  everyCandidateIncomplete :=
    genericOrbit_everyCandidateIncomplete patchable initial

end PatchableArithmeticTarskiContext
end ClosedStabilityTheorem
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.GenericOrbitInvariant
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.genericOrbitInvariant
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.genericOrbitIndex_injective
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.genericOrbitCandidate_injective
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.genericDynamicOrbitCandidate_injective
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.genericOrbit_noExactReturn
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.genericDynamicOrbit_noExactReturn
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.GenericPatchOrbitTheorem
#print axioms Meta.ClosedStabilityTheorem.PatchableArithmeticTarskiContext.genericPatchOrbitTheorem
/- AXIOM_AUDIT_END -/
