import Carbone.CW0.Lean.CoreAdapter

/-!
# CW0: a concrete two-phase carbon/Core witness

This file closes the first executable architectural loop.  Its two finite
carbon organizations have the same visible atom inventory and distinct bond
skeletons.  A repair alternates between them while preserving the environment
and total inventory and extending the internal history.

The construction is deliberately only a structural witness.  It does not
assert that the two skeletons are chemical species or that their alternation is
a physically admissible reaction.
-/

namespace Meta
namespace Carbone
namespace CW0

open ClosedStabilityTheorem
open DynamicRelaxedUsage
open RelaxedSemantics

inductive TwoPhase where
  | chain
  | bridged
deriving DecidableEq, Repr

def TwoPhase.other : TwoPhase -> TwoPhase
  | .chain => .bridged
  | .bridged => .chain

def TwoPhase.organization : TwoPhase -> CarbonOrganization
  | .chain => chainOrganization
  | .bridged => bridgedOrganization

def twoPhaseEnvironment : CarbonEnvironment where
  resources := AtomInventory.zero
  energyTokens := 1
  compartmentCapacity := 1

def twoPhaseState
    (phase : TwoPhase)
    (history : List HistoryRecord) : WorldState where
  organization := phase.organization
  environment := twoPhaseEnvironment
  history := history

/-- Positive admissibility data: every state is generated by one phase and its history. -/
inductive TwoPhaseAdmissible : WorldState -> Type where
  | generated (phase : TwoPhase) (history : List HistoryRecord) :
      TwoPhaseAdmissible (twoPhaseState phase history)

def twoPhaseTag : TwoPhase -> Nat
  | .chain => 0
  | .bridged => 1

def twoPhaseRecord (phase : TwoPhase) : HistoryRecord where
  gapTag := twoPhaseTag phase
  interactionTag := twoPhaseTag phase
  responseTag := twoPhaseTag phase

theorem bridgedOrganization_ne_chainOrganization :
    bridgedOrganization = chainOrganization -> False := by
  intro equality
  exact chainOrganization_ne_bridgedOrganization equality.symm

def twoPhaseGap
    (phase : TwoPhase)
    (history : List HistoryRecord) :
    CarbonGap (twoPhaseState phase history) where
  tag := twoPhaseTag phase
  shadow := phase.other.organization
  sameProjection := by
    cases phase <;> rfl
  separated := by
    cases phase with
    | chain => exact chainOrganization_ne_bridgedOrganization
    | bridged => exact bridgedOrganization_ne_chainOrganization

def twoPhaseInteraction
    (phase : TwoPhase)
    (history : List HistoryRecord) :
    CarbonInteraction
      (twoPhaseState phase history)
      (twoPhaseGap phase history) where
  tag := twoPhaseTag phase
  requestedResources := AtomInventory.zero
  requestedEnergy := 0
  resourcesAvailable :=
    ⟨ Nat.zero_le _
    , Nat.zero_le _
    , Nat.zero_le _
    , Nat.zero_le _
    , Nat.zero_le _
    , Nat.zero_le _ ⟩
  energyAvailable := Nat.zero_le _

def twoPhaseResponse
    (phase : TwoPhase)
    (history : List HistoryRecord) :
    CarbonResponse
      (twoPhaseState phase history)
      (twoPhaseInteraction phase history) where
  tag := twoPhaseTag phase
  afterOrganization := phase.other.organization
  afterEnvironment := twoPhaseEnvironment
  inventoryBalanced := by
    cases phase <;> rfl
  energyNonincreasing := Nat.le_refl _

def twoPhaseCausalStep
    (phase : TwoPhase)
    (history : List HistoryRecord) :
    CarbonCausalStep (twoPhaseState phase history) where
  gap := twoPhaseGap phase history
  interaction := twoPhaseInteraction phase history
  response := twoPhaseResponse phase history
  record := twoPhaseRecord phase
  recordGap_eq := rfl
  recordInteraction_eq := rfl
  recordResponse_eq := rfl

def twoPhaseCausalStepAt
    (source : WorldState)
    (admissible : TwoPhaseAdmissible source) :
    CarbonCausalStep source :=
  match admissible with
  | .generated phase history => twoPhaseCausalStep phase history

def twoPhaseClosedUnderRepair
    (source : WorldState)
    (admissible : TwoPhaseAdmissible source) :
    TwoPhaseAdmissible
      (executeRepair
        source
        (repairOfCausalStep (twoPhaseCausalStepAt source admissible))) := by
  cases admissible with
  | generated phase history =>
      cases phase with
      | chain =>
          exact
            TwoPhaseAdmissible.generated
              .bridged
              (history ++ [twoPhaseRecord .chain])
      | bridged =>
          exact
            TwoPhaseAdmissible.generated
              .chain
              (history ++ [twoPhaseRecord .bridged])

/-- A closed, executable carbon world with two structural phases. -/
def twoPhaseWorld : CarbonWorld where
  Admissible := TwoPhaseAdmissible
  initial := twoPhaseState .chain []
  initialAdmissible := TwoPhaseAdmissible.generated .chain []
  causalStepAt := twoPhaseCausalStepAt
  closedUnderRepair := twoPhaseClosedUnderRepair

def twoPhaseShadowPointOfAdmissible
    {source : WorldState}
    (admissible : TwoPhaseAdmissible source) : twoPhaseWorld.Point :=
  match admissible with
  | .generated phase history =>
      @Sigma.mk
        WorldState
        twoPhaseWorld.Admissible
        (twoPhaseState phase.other history)
        (TwoPhaseAdmissible.generated phase.other history)

def twoPhaseShadowPoint
    (point : twoPhaseWorld.Point) : twoPhaseWorld.Point :=
  twoPhaseShadowPointOfAdmissible point.2

theorem twoPhasePoint_sameProjection_shadow
    (point : twoPhaseWorld.Point) :
    pointProject twoPhaseWorld point =
      pointProject twoPhaseWorld (twoPhaseShadowPoint point) := by
  rcases point with ⟨source, admissible⟩
  cases admissible with
  | generated phase history =>
      cases phase <;> rfl

theorem twoPhasePoint_ne_shadow
    (point : twoPhaseWorld.Point) :
    point = twoPhaseShadowPoint point -> False := by
  rcases point with ⟨source, admissible⟩
  cases admissible with
  | generated phase history =>
      intro equality
      have organizationEquality :=
        congrArg
          (fun current : twoPhaseWorld.Point => current.1.organization)
          equality
      cases phase with
      | chain =>
          exact
            chainOrganization_ne_bridgedOrganization organizationEquality
      | bridged =>
          exact
            bridgedOrganization_ne_chainOrganization organizationEquality

/-! ## A typed bilateral carrier retaining the current carbon point -/

structure TwoPhaseComplete (_branch : Unit) where
  point : twoPhaseWorld.Point

structure TwoPhaseForward (_branch : Unit) where
  point : twoPhaseWorld.Point

structure TwoPhaseBackward (_branch : Unit) where
  point : twoPhaseWorld.Point

structure TwoPhaseIntersection (_branch : Unit) where
  point : twoPhaseWorld.Point

def twoPhaseCompleteness : BidirectionalCompleteness Unit where
  Complete := TwoPhaseComplete
  Forward := TwoPhaseForward
  Backward := TwoPhaseBackward
  Intersection := TwoPhaseIntersection
  forwardOfComplete := fun _ complete => ⟨complete.point⟩
  backwardOfComplete := fun _ complete => ⟨complete.point⟩
  intersectionOfComplete := fun _ complete => ⟨complete.point⟩
  completeOfIntersection := fun _ intersection => ⟨intersection.point⟩

def twoPhaseRoundTripCoherence :
    RoundTripCoherence twoPhaseCompleteness where
  completeRoundTrip :=
    { complete_stable := by
        intro branch complete
        cases complete
        rfl }
  intersectionRoundTrip :=
    { intersection_stable := by
        intro branch intersection
        cases intersection
        rfl }

/-- The interface witness stores the exact admissible point it witnesses. -/
structure TwoPhaseInterfaceWitness
    (interface : twoPhaseWorld.Point) where
  point : twoPhaseWorld.Point
  point_eq_interface : point = interface

def twoPhaseInterfaceWitnessAt
    (point : twoPhaseWorld.Point) :
    TwoPhaseInterfaceWitness point where
  point := point
  point_eq_interface := rfl

/-- Realization ties the formed interface to the source intersection. -/
structure TwoPhaseRealizesInterface
    (cycle :
      StrongTerminalCycleFromIntersection twoPhaseCompleteness ())
    (interface : twoPhaseWorld.Point) where
  token : Unit
  interface_eq_intersection :
    interface = cycle.sourceIntersection.point

def twoPhaseRealizesAt
    (point : twoPhaseWorld.Point) :
    TwoPhaseRealizesInterface
      (strongTerminalCycleFromIntersection
        twoPhaseCompleteness
        twoPhaseRoundTripCoherence
        (TwoPhaseIntersection.mk point))
      point where
  token := ()
  interface_eq_intersection := rfl

def twoPhaseCanonicalRepairAt
    (point : twoPhaseWorld.Point) :
    CanonicalRepairAt twoPhaseWorld point where
  repair := twoPhaseWorld.repairAt point
  repair_eq := rfl

def twoPhaseLocalRecovery
    (point : twoPhaseWorld.Point) :
    LocalProjectiveRecovery
      twoPhaseWorld.Point
      CarbonVisible
      (pointProject twoPhaseWorld)
      (CanonicalRepairAt twoPhaseWorld) where
  formed := point
  shadow := twoPhaseShadowPoint point
  sameProjection := twoPhasePoint_sameProjection_shadow point
  separated := twoPhasePoint_ne_shadow point
  repair := twoPhaseCanonicalRepairAt point
  recovered := point
  recovered_eq_formed := rfl

def twoPhaseDynamicReturn
    (point : twoPhaseWorld.Point) :
    LocallyRecoveredDynamicReturn
      twoPhaseCompleteness
      twoPhaseRoundTripCoherence
      ()
      twoPhaseWorld.Point
      twoPhaseWorld.Point
      TwoPhaseInterfaceWitness
      TwoPhaseRealizesInterface
      CarbonVisible
      (pointProject twoPhaseWorld)
      (CanonicalRepairAt twoPhaseWorld) where
  formedReturn :=
    { source := point
      intersection := TwoPhaseIntersection.mk point }
  formed :=
    { interface := point
      witness := twoPhaseInterfaceWitnessAt point }
  realizes := twoPhaseRealizesAt point
  localRecovery := twoPhaseLocalRecovery point
  localRecovery_sameInterface := rfl

/-- A concrete intrinsic family over every admissible two-phase source. -/
def twoPhaseIntrinsicFamily :
    IntrinsicDynamicReturnFamily
      twoPhaseCompleteness
      twoPhaseRoundTripCoherence
      ()
      twoPhaseWorld.Point
      twoPhaseWorld.Point
      TwoPhaseInterfaceWitness
      TwoPhaseRealizesInterface
      CarbonVisible
      (pointProject twoPhaseWorld)
      (CanonicalRepairAt twoPhaseWorld) where
  initial := twoPhaseWorld.initialPoint
  returnAt := twoPhaseDynamicReturn
  returnAt_source := fun _ => rfl

/-- The abstract carbon/Core adapter is inhabited by the concrete family. -/
def twoPhaseCoreAtlas :
    CarbonCoreAtlas
      twoPhaseCompleteness
      twoPhaseRoundTripCoherence
      ()
      twoPhaseWorld
      TwoPhaseInterfaceWitness
      TwoPhaseRealizesInterface where
  family := twoPhaseIntrinsicFamily
  formedAt_eq_source := fun _ => rfl

/-- The resulting Core algebra has no separately supplied successor. -/
def twoPhaseGapRepairAlgebra :
    GapRepairAlgebra twoPhaseIntrinsicFamily :=
  twoPhaseCoreAtlas.toGapRepairAlgebra

theorem twoPhaseCoreStep_organization
    (phase : TwoPhase)
    (history : List HistoryRecord) :
    (twoPhaseGapRepairAlgebra.next
        ⟨ twoPhaseState phase history
        , TwoPhaseAdmissible.generated phase history ⟩).1.organization =
      phase.other.organization := by
  cases phase <;> rfl

theorem twoPhaseCoreStep_history
    (phase : TwoPhase)
    (history : List HistoryRecord) :
    (twoPhaseGapRepairAlgebra.next
        ⟨ twoPhaseState phase history
        , TwoPhaseAdmissible.generated phase history ⟩).1.history =
      history ++ [twoPhaseRecord phase] := by
  cases phase <;> rfl

theorem twoPhaseInitialCoreStep_organization :
    (twoPhaseGapRepairAlgebra.next twoPhaseWorld.initialPoint).1.organization =
      bridgedOrganization :=
  rfl

theorem twoPhaseInitialCoreStep_history :
    (twoPhaseGapRepairAlgebra.next twoPhaseWorld.initialPoint).1.history =
      [twoPhaseRecord .chain] :=
  rfl

theorem twoPhaseInitialCoreStep_preservesInventory :
    totalInventory
        (twoPhaseGapRepairAlgebra.next twoPhaseWorld.initialPoint).1 =
      totalInventory twoPhaseWorld.initial := by
  calc
    totalInventory
        (twoPhaseGapRepairAlgebra.next twoPhaseWorld.initialPoint).1 =
        totalInventory (twoPhaseWorld.step twoPhaseWorld.initialPoint).1 :=
      congrArg
        totalInventory
        (twoPhaseCoreAtlas.coreNext_source_eq_worldStep
          twoPhaseWorld.initialPoint)
    _ = totalInventory twoPhaseWorld.initialPoint.1 :=
      twoPhaseWorld.step_totalInventory twoPhaseWorld.initialPoint
    _ = totalInventory twoPhaseWorld.initial := rfl

theorem twoPhaseInitialCoreStep_changesOrganization :
    (twoPhaseGapRepairAlgebra.next twoPhaseWorld.initialPoint).1.organization =
      twoPhaseWorld.initial.organization ->
    False := by
  intro equality
  exact bridgedOrganization_ne_chainOrganization equality

end CW0
end Carbone
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.Carbone.CW0.twoPhaseCoreAtlas
#print axioms Meta.Carbone.CW0.twoPhaseCoreStep_organization
#print axioms Meta.Carbone.CW0.twoPhaseCoreStep_history
#print axioms Meta.Carbone.CW0.twoPhaseInitialCoreStep_preservesInventory
#print axioms Meta.Carbone.CW0.twoPhaseInitialCoreStep_changesOrganization
/- AXIOM_AUDIT_END -/
