import Meta.Tarski.BareArithmetic.Patch
import Meta.Tarski.VisibleCausalRecurrence

/-!
# Closed bare-arithmetic Tarski instance

This module is the first closed instantiation of the generic orbit whose
sentences and predicates are ordinary first-order arithmetic syntax and whose
diagonalizer is obtained from represented capture-avoiding substitution.
-/

namespace Meta
namespace BareArithmeticTarski

open ClosedStabilityTheorem
open ClosedStabilityTheorem.PatchableArithmeticTarskiContext

/-! ## Closed contexts -/

/-- Genuine arithmetic Tarski context over standard natural-number semantics. -/
def bareArithmeticTarskiContext : ArithmeticTarskiContext where
  Sentence := Sentence
  Predicate := Predicate
  applyQuote := fun predicate sentence =>
    predicate.applyNumeral sentence.quote
  models := Sentence.models
  diagonal := diagonal
  diagonal_spec := diagonal_spec

/-- Bare arithmetic syntax is internally closed under local Tarski repair. -/
def bareArithmeticPatchableContext : PatchableArithmeticTarskiContext where
  context := bareArithmeticTarskiContext
  patchPredicate := patch
  patch_agrees_at := patch_agrees_at
  patch_preserves_off_index := patch_preserves_off_index

/-- Constantly false ordinary arithmetic predicate. -/
def initialBareArithmeticPredicate : Predicate := falsePredicate

/-! ## Specialized generic and causal theorems -/

/-- Closed generic orbit theorem for the genuine arithmetic instance. -/
def bareArithmeticGenericPatchOrbitTheorem :
    GenericPatchOrbitTheorem
      bareArithmeticPatchableContext
      initialBareArithmeticPredicate :=
  genericPatchOrbitTheorem
    bareArithmeticPatchableContext
    initialBareArithmeticPredicate

/-- Closed visible-recurrence and causal-non-return theorem. -/
def bareArithmeticVisibleCausalNonRecurrenceTheorem :
    GenericVisibleCausalNonRecurrenceTheorem
      bareArithmeticPatchableContext
      initialBareArithmeticPredicate :=
  genericVisibleCausalNonRecurrenceTheorem
    bareArithmeticPatchableContext
    initialBareArithmeticPredicate

/-- Candidate and challenge at the indicated arithmetic orbit position. -/
def bareArithmeticOrbitCandidate (n : Nat) : Predicate :=
  genericOrbitCandidate
    bareArithmeticPatchableContext
    initialBareArithmeticPredicate
    n

def bareArithmeticOrbitIndex (n : Nat) : Sentence :=
  genericOrbitIndex
    bareArithmeticPatchableContext
    initialBareArithmeticPredicate
    n

/-! ## Explicit non-vacuity -/

/-- Closed true arithmetic sentence `0 = 0`. -/
def bareTrueSentence : Sentence where
  raw := RawFormula.equal RawTerm.zero RawTerm.zero
  isScoped := And.intro trivial trivial

/-- Closed false arithmetic sentence. -/
def bareFalseSentence : Sentence := falseSentence

def bareTrueSentence_models : bareTrueSentence.models := rfl

theorem bareFalseSentence_not_models :
    bareFalseSentence.models -> False := by
  intro impossible
  exact impossible

theorem bareModels_nonconstant
    (sameTruth : bareTrueSentence.models ↔ bareFalseSentence.models) :
    False :=
  bareFalseSentence_not_models
    (sameTruth.mp bareTrueSentence_models)

/-- Positive grammar certificate containing exactly the ordinary constructors. -/
inductive OrdinaryFormula : RawFormula -> Type
  | falsum : OrdinaryFormula RawFormula.falsum
  | equal (left right : RawTerm) :
      OrdinaryFormula (RawFormula.equal left right)
  | conj {left right : RawFormula} :
      OrdinaryFormula left -> OrdinaryFormula right ->
      OrdinaryFormula (RawFormula.conj left right)
  | disj {left right : RawFormula} :
      OrdinaryFormula left -> OrdinaryFormula right ->
      OrdinaryFormula (RawFormula.disj left right)
  | impl {left right : RawFormula} :
      OrdinaryFormula left -> OrdinaryFormula right ->
      OrdinaryFormula (RawFormula.impl left right)
  | all {body : RawFormula} :
      OrdinaryFormula body -> OrdinaryFormula (RawFormula.all body)
  | ex {body : RawFormula} :
      OrdinaryFormula body -> OrdinaryFormula (RawFormula.ex body)

/-- Every raw formula is positively generated by the ordinary grammar. -/
def ordinaryFormula : (formula : RawFormula) -> OrdinaryFormula formula
  | RawFormula.falsum => OrdinaryFormula.falsum
  | RawFormula.equal left right => OrdinaryFormula.equal left right
  | RawFormula.conj left right =>
      OrdinaryFormula.conj (ordinaryFormula left) (ordinaryFormula right)
  | RawFormula.disj left right =>
      OrdinaryFormula.disj (ordinaryFormula left) (ordinaryFormula right)
  | RawFormula.impl left right =>
      OrdinaryFormula.impl (ordinaryFormula left) (ordinaryFormula right)
  | RawFormula.all body => OrdinaryFormula.all (ordinaryFormula body)
  | RawFormula.ex body => OrdinaryFormula.ex (ordinaryFormula body)

/-- The constructed diagonal is certified as ordinary non-reflective syntax. -/
def bareDiagonalOrdinary (predicate : Predicate) :
    OrdinaryFormula (diagonal predicate).raw :=
  ordinaryFormula (diagonal predicate).raw

/-- The first arithmetic repair changes the candidate syntax. -/
theorem bareInitialCandidate_ne_first
    (sameCandidate :
      bareArithmeticOrbitCandidate 0 = bareArithmeticOrbitCandidate 1) :
    False := by
  have sameIteration :=
    bareArithmeticGenericPatchOrbitTheorem.syntaxOrbitSeparated sameCandidate
  exact Nat.noConfusion sameIteration

/-- Every two distinct iterations have different predicate syntax. -/
theorem bareOrbitCandidate_ne_of_ne
    {left right : Nat}
    (different : left = right -> False)
    (sameCandidate :
      bareArithmeticOrbitCandidate left =
        bareArithmeticOrbitCandidate right) :
    False :=
  different
    (bareArithmeticGenericPatchOrbitTheorem.syntaxOrbitSeparated sameCandidate)

/-- Every two distinct iterations have different diagonal challenges. -/
theorem bareOrbitIndex_ne_of_ne
    {left right : Nat}
    (different : left = right -> False)
    (sameIndex :
      bareArithmeticOrbitIndex left = bareArithmeticOrbitIndex right) :
    False :=
  different
    (bareArithmeticGenericPatchOrbitTheorem.indicesSeparated sameIndex)

/-- Each patch changes the semantic answer at the current diagonal challenge. -/
theorem bareOrbit_semanticChangeAtCurrent
    (n : Nat)
    (sameTruth :
      bareArithmeticPatchableContext.truthAt
          (bareArithmeticOrbitCandidate n)
          (bareArithmeticOrbitIndex n) ↔
        bareArithmeticPatchableContext.truthAt
          (bareArithmeticOrbitCandidate (Nat.succ n))
          (bareArithmeticOrbitIndex n)) :
    False := by
  apply bareArithmeticGenericPatchOrbitTheorem.currentMismatch n
  exact sameTruth.trans
    (bareArithmeticGenericPatchOrbitTheorem.cumulativeAgreement
      (Nat.lt_succ_self n))

/-- Closed certificate that the instance is semantically and dynamically nontrivial. -/
structure BareArithmeticNontriviality : Type where
  trueSentenceModeled : bareTrueSentence.models
  falseSentenceRefuted : bareFalseSentence.models -> False
  semanticValuesSeparated :
    (bareTrueSentence.models ↔ bareFalseSentence.models) -> False
  quotationInjective : Function.Injective Sentence.quote
  firstStepSeparated :
    bareArithmeticOrbitCandidate 0 = bareArithmeticOrbitCandidate 1 -> False
  allCandidatesSeparated :
    forall {left right : Nat},
      (left = right -> False) ->
      bareArithmeticOrbitCandidate left =
        bareArithmeticOrbitCandidate right -> False
  allIndicesSeparated :
    forall {left right : Nat},
      (left = right -> False) ->
      bareArithmeticOrbitIndex left = bareArithmeticOrbitIndex right -> False
  everyStepChangesSemantics :
    forall n : Nat,
      (bareArithmeticPatchableContext.truthAt
          (bareArithmeticOrbitCandidate n)
          (bareArithmeticOrbitIndex n) ↔
        bareArithmeticPatchableContext.truthAt
          (bareArithmeticOrbitCandidate (Nat.succ n))
          (bareArithmeticOrbitIndex n)) -> False
  diagonalUsesOrdinaryGrammar :
    (predicate : Predicate) -> OrdinaryFormula (diagonal predicate).raw

/-- Canonical nontriviality witness. -/
def bareArithmeticNontriviality : BareArithmeticNontriviality where
  trueSentenceModeled := bareTrueSentence_models
  falseSentenceRefuted := bareFalseSentence_not_models
  semanticValuesSeparated := bareModels_nonconstant
  quotationInjective := Sentence.quote_injective
  firstStepSeparated := bareInitialCandidate_ne_first
  allCandidatesSeparated := bareOrbitCandidate_ne_of_ne
  allIndicesSeparated := bareOrbitIndex_ne_of_ne
  everyStepChangesSemantics := bareOrbit_semanticChangeAtCurrent
  diagonalUsesOrdinaryGrammar := bareDiagonalOrdinary

/-- One closed value containing the instance and both non-return packages. -/
structure BareArithmeticTarskiClosedSystem : Type where
  orbitTheorem :
    GenericPatchOrbitTheorem
      bareArithmeticPatchableContext
      initialBareArithmeticPredicate
  visibleCausalTheorem :
    GenericVisibleCausalNonRecurrenceTheorem
      bareArithmeticPatchableContext
      initialBareArithmeticPredicate
  nontriviality : BareArithmeticNontriviality

/-- Fully closed Foundation-independent arithmetic realization. -/
def bareArithmeticTarskiClosedSystem : BareArithmeticTarskiClosedSystem where
  orbitTheorem := bareArithmeticGenericPatchOrbitTheorem
  visibleCausalTheorem := bareArithmeticVisibleCausalNonRecurrenceTheorem
  nontriviality := bareArithmeticNontriviality

end BareArithmeticTarski
end Meta

/- AXIOM_AUDIT_BEGIN -/
#print axioms Meta.BareArithmeticTarski.bareArithmeticTarskiContext
#print axioms Meta.BareArithmeticTarski.bareArithmeticPatchableContext
#print axioms Meta.BareArithmeticTarski.bareArithmeticGenericPatchOrbitTheorem
#print axioms Meta.BareArithmeticTarski.bareArithmeticVisibleCausalNonRecurrenceTheorem
#print axioms Meta.BareArithmeticTarski.bareArithmeticNontriviality
#print axioms Meta.BareArithmeticTarski.bareArithmeticTarskiClosedSystem
/- AXIOM_AUDIT_END -/
